다양한 임베딩 모델을 평가하는 구체적인 방법을 알려드리도록 하겠습니다
- 임베딩 후보 리스트 준비 (OpenAI, Cohere, e5-base-v2)
- 활용하고자 하는 데이터셋을 임베딩 변환
- Test set 랜덤 선별 후 평가 지표 생성

---

In [3]:
!pip install cohere gensim numpy pandas scikit-learn matplotlib seaborn

zsh:1: /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/bin/pip: bad interpreter: /Users/igyeongseob/Develop/ai/vector/venv/bin/python3: no such file or directory
Collecting cohere
  Using cached cohere-5.20.2-py3-none-any.whl.metadata (3.5 kB)
Collecting gensim
  Using cached gensim-4.4.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (2.3.4)
Requirement already satisfied: pandas in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: scikit-learn in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (1.7.2)
Requirement already satisfied: matplotlib in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (3.10.7)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting fastavro<2.0.0,>=1.9.4 (from cohere)
  Using cached fastavro-1.12.1-cp312-cp312-macosx_10_13_universal2.whl.metadata (5.8 kB)
Requirement already satisfied: httpx>=0.21.2 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from cohere) (0.28.1)
Requirement already satisfied: pydantic>=1.9.2 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from cohere) (2.12.4)
Requirement already satisfied: pydantic-core>=2.18.2 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from cohere) (2.41.5)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from cohere) (2.32.5)
Requirement already satisfied: tokenizers<1,>=0.15 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from cohere) (0.22.1)
Requirement already satisfied: types-requests<3.0.0,>=2.0.0 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from cohere) (2.32.4.20250913)
Requirement already satisfied: typing_extensions>=4.0.0 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from cohere) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->cohere) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->cohere) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->cohere) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->cohere) (2025.11.12)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from tokenizers<1,>=0.15->cohere) (0.36.0)
Requirement already satisfied: filelock in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (2025.10.0)
Requirement already satisfied: packaging>=20.9 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (1.2.0)
Requirement already satisfied: scipy>=1.7.0 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from gensim) (1.16.3)
Collecting smart_open>=1.8.1 (from gensim)
  Using cached smart_open-7.5.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: anyio in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from httpx>=0.21.2->cohere) (4.11.0)
Requirement already satisfied: httpcore==1.* in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from httpx>=0.21.2->cohere) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.21.2->cohere) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from pydantic>=1.9.2->cohere) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from pydantic>=1.9.2->cohere) (0.4.2)
Requirement already satisfied: six>=1.5 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: wrapt in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from smart_open>=1.8.1->gensim) (1.17.3)
Requirement already satisfied: sniffio>=1.1 in /Users/igyeongseob/.pyenv/versions/3.12.6/lib/python3.12/site-packages (from anyio->httpx>=0.21.2->cohere) (1.3.1)
Downloading cohere-5.20.2-py3-none-any.whl (318 kB)
Using cached fastavro-1.12.1-cp312-cp312-macosx_10_13_universal2.whl (1.0 MB)
Using cached gensim-4.4.0-cp312-cp312-macosx_11_0_arm64.whl (24.5 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached smart_open-7.5.0-py3-none-any.whl (63 kB)
Installing collected packages: smart_open, fastavro, gensim, seaborn, cohere
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [cohere]2m4/5 [cohere]]
Successfully installed cohere-5.20.2 fastavro-1.12.1 gensim-4.4.0 seaborn-0.13.2 smart_open-7.5.0

In [1]:
import pandas as pd
import os
import random
import cohere
import torch
import numpy as np
from transformers import AutoModel, AutoTokenizer
import openai
from openai import OpenAI
from tqdm.notebook import tqdm
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# initialize openai
from dotenv import load_dotenv
load_dotenv()
openai.api_key = os.environ["OPENAI_API_KEY"]

# initialize cohere
co = cohere.Client()

import warnings
warnings.filterwarnings('ignore')

### Read dataset

In [ ]:
df = pd.read_csv("dataset/abcnews.csv")

In [ ]:
df

         publish_date                                      headline_text
0            20030219  aba decides against community broadcasting lic...
1            20030219     act fire witnesses must be aware of defamation
2            20030219     a g calls for infrastructure protection summit
3            20030219           air nz staff in aust strike for pay rise
4            20030219      air nz strike to affect australian travellers
...               ...                                                ...
1244179      20211231  two aged care residents die as state records 2...
1244180      20211231  victoria records 5;919 new cases and seven deaths
1244181      20211231    wa delays adopting new close contact definition
1244182      20211231  western ringtail possums found badly dehydrate...
1244183      20211231  what makes you a close covid contact here are ...

[1244184 rows x 2 columns]

In [ ]:
df.head()

   publish_date                                      headline_text
0      20030219  aba decides against community broadcasting lic...
1      20030219     act fire witnesses must be aware of defamation
2      20030219     a g calls for infrastructure protection summit
3      20030219           air nz staff in aust strike for pay rise
4      20030219      air nz strike to affect australian travellers

### 1. Playground

In [ ]:
text1 = df.loc[2, 'headline_text']
print(text1)

a g calls for infrastructure protection summit

In [ ]:
text2 = df.loc[3, 'headline_text']
print(text2)

air nz staff in aust strike for pay rise

In [ ]:
def create_embeddings(txt_list, provider='openai'):
    if provider=='openai':
        client = OpenAI()

        response = client.embeddings.create(
        input=txt_list,
        model="text-embedding-3-small")
        responses = [r.embedding for r in response.data]

        return responses
    
    elif provider=='cohere':
        doc_embeds = co.embed(
        txt_list,
        input_type="search_document",
        model="embed-english-v3.0")
        return doc_embeds.embeddings
    else:
        assert False, "Double check provider name"

In [ ]:
emb1 = create_embeddings(df.loc[2, 'headline_text'])
emb2 = create_embeddings(df.loc[3, 'headline_text'])

In [ ]:
from utils import cosine_similarity

In [ ]:
# simarity between two embeddings
print("Cosine 유사도 : {}.\n사용된 문장 : \n{}\n{}".format(cosine_similarity(emb1[0], emb2[0]), text1, text2))

Cosine 유사도 : 0.16141813010923994.
사용된 문장 :
a g calls for infrastructure protection summit
air nz staff in aust strike for pay rise

In [ ]:
text3 = df.loc[4, 'headline_text']

emb3 = create_embeddings(text3)
print("Cosine 유사도 : {}.\n사용된 문장 : \n{}\n{}".format(cosine_similarity(emb1[0], emb3[0]), text1, text3))

Cosine 유사도 : 0.15100410380900078.
사용된 문장 :
a g calls for infrastructure protection summit
air nz strike to affect australian travellers

In [ ]:
text4 = df.loc[6, 'headline_text']

emb3 = create_embeddings(text4)
print("Cosine 유사도 : {}.\n사용된 문장 : \n{}\n{}".format(cosine_similarity(emb1[0], emb3[0]), text1, text4))

Cosine 유사도 : 0.1365442494556233.
사용된 문장 :
a g calls for infrastructure protection summit
antic delighted with record breaking barca

---

### 2. Embedding vector Dataset 만들기

openai embeddings

In [ ]:
# create embeddings (openai)
# (비용 발생 주의)
MAX_ITEMS = 10 # 원하는 개수 제한

texts = (
    df["headline_text"]
    .dropna()
    .astype(str)
    .head(MAX_ITEMS)
    .tolist()
)

openai_emb = create_embeddings(
    texts,
    provider="openai"
)

In [ ]:
texts

['aba decides against community broadcasting licence',
 'act fire witnesses must be aware of defamation',
 'a g calls for infrastructure protection summit',
 'air nz staff in aust strike for pay rise',
 'air nz strike to affect australian travellers',
 'ambitious olsson wins triple jump',
 'antic delighted with record breaking barca',
 'aussie qualifier stosur wastes four memphis match',
 'aust addresses un security council over iraq',
 'australia is locked into war timetable opp']

In [ ]:
# df['openai_emb'] = openai_emb
openai_emb

[[0.02436016872525215,
  0.010141161270439625,
  0.07135467231273651,
  0.0008161420118995011,
  -0.02599436044692993,
  0.025856906548142433,
  -0.0004944579559378326,
  0.013134635984897614,
  0.011928082443773746,
  0.03512751683592796,
  0.02159578539431095,
  -0.05113344267010689,
  -0.032225675880908966,
  0.05247745290398598,
  0.04377193748950958,
  0.005280581768602133,
  0.024253258481621742,
  -0.0006300043314695358,
  -0.04502430930733681,
  0.008254965767264366,
  -0.015234651044011116,
  0.021580513566732407,
  -0.013745549134910107,
  -0.013455365784466267,
  -0.030148571357131004,
  -0.03732680156826973,
  -0.027032913640141487,
  -0.00833896640688181,
  0.028957290574908257,
  -0.0034707512240856886,
  0.03772389516234398,
  -0.053852006793022156,
  -0.01617392897605896,
  0.021656876429915428,
  -0.018296852707862854,
  -0.0016093747690320015,
  -0.0024474714882671833,
  -0.026269271969795227,
  0.001305827172473073,
  -0.044107940047979355,
  -0.027689645066857338,
  -0.04172537848353386,
  0.011813536286354065,
  -0.008247329853475094,
  -0.020847417414188385,
  0.03097330406308174,
  -0.031889673322439194,
  0.03439442068338394,
  -0.003955663647502661,
  0.01570047251880169,
  0.03366132453083992,
  0.03964827209711075,
  0.003741844091564417,
  0.002193560590967536,
  -0.01352409366518259,
  -0.015127740800380707,
  -0.0012962816981598735,
  -0.01785394176840782,
  0.014394644647836685,
  -0.0004822874325327575,
  0.025780541822314262,
  -0.004864397458732128,
  0.0653066337108612,
  0.012737542390823364,
  -0.014318280853331089,
  -0.03573842719197273,
  -0.0027281097136437893,
  0.0334475040435791,
  -0.002940020291134715,
  0.015929564833641052,
  -0.04068682715296745,
  -0.03540242463350296,
  0.016662660986185074,
  -0.0545240119099617,
  -0.028285285457968712,
  0.04233629256486893,
  0.03115657903254032,
  0.00665131863206625,
  0.00459712278097868,
  0.015081922523677349,
  -0.005383673589676619,
  0.08051837235689163,
  -0.03427223488688469,
  -0.013623367063701153,
  0.019365951418876648,
  0.008682605810463428,
  -0.06775028258562088,
  0.0007225958979688585,
  0.011676080524921417,
  -0.010782619938254356,
  -0.02781182900071144,
  0.03692970797419548,
  -0.0306831207126379,
  0.008568058721721172,
  0.022374700754880905,
  0.01709030009806156,
  0.03500533103942871,
  0.015975382179021835,
  0.07129358500242233,
  -0.004684941377490759,
  -0.02460453286767006,
  -9.527622751193121e-05,
  -0.027231460437178612,
  -0.00801823753863573,
  0.013424820266664028,
  0.004830033518373966,
  -0.012997180223464966,
  0.013951732777059078,
  -0.00807169172912836,
  0.010133524425327778,
  -0.025200173258781433,
  -0.021794332191348076,
  -0.0043107569217681885,
  0.025536175817251205,
  -0.011462260968983173,
  -0.03463878482580185,
  0.044077396392822266,
  -0.049056340008974075,
  0.05779239907860756,
  -0.0038392082788050175,
  -0.006292406935244799,
  0.05095016956329346,
  0.0008008691947907209,
  0.012279357761144638,
  0.059044770896434784,
  0.051713813096284866,
  0.02465035207569599,
  0.0518970862030983,
  -0.057089850306510925,
  -0.07502015680074692,
  0.05299672856926918,
  0.011225531809031963,
  -0.007750962395220995,
  0.02391725592315197,
  -0.050186529755592346,
  0.04221411049365997,
  -0.032836589962244034,
  0.013623367063701153,
  -0.020480869337916374,
  -0.03137039765715599,
  0.06854446977376938,
  0.01846485398709774,
  0.014371735975146294,
  -0.060541510581970215,
  -0.06573427468538284,
  0.014646646566689014,
  0.005463855806738138,
  -0.031141305342316628,
  0.005864767823368311,
  -0.030224936082959175,
  -0.0063496800139546394,
  -0.014219007454812527,
  -0.05415746569633484,
  -0.020129593089222908,
  -0.01941177062690258,
  -0.029232202097773552,
  0.019075768068432808,
  -0.016876479610800743,
  -0.01667793281376362,
  -0.002943838480859995,
  -0.020419778302311897,
  -0.03079003095626831,
  -0.03439442068338394,
  0.029507113620638847,
  0.03326423093676567,
  0.04361921176314354,
  -0.011683717370033264,
  -0.020083775743842125,
  -0.05513492599129677,
  0.011256077326834202,
  -0.01893831230700016,
  0.013004817068576813,
  0.001775466836988926,
  0.021794332191348076,
  0.0028254741337150335,
  -0.015899019315838814,
  0.06124405935406685,
  -0.06274079531431198,
  0.006044223438948393,
  -0.06891102343797684,
  0.005666221026331186,
  0.024879444390535355,
  0.005902949720621109,
  -0.018907766789197922,
  -0.02336743474006653,
  0.02584163285791874,
  -0.01970195397734642,
  -0.01825103536248207,
  0.02217615395784378,
  -0.0037819352000951767,
  -0.010362616740167141,
  0.025459812954068184,
  0.03521915152668953,
  0.014807011000812054,
  0.025016900151968002,
  -0.007395869120955467,
  -0.0037284803111106157,
  0.020587777718901634,
  -0.0030889303889125586,
  -0.010179342702031136,
  0.013730276376008987,
  -0.023795073851943016,
  0.01948813535273075,
  0.02006850205361843,
  -0.053852006793022156,
  -0.030927486717700958,
  -0.01472301036119461,
  -0.011706626042723656,
  0.007747144438326359,
  -0.006758228410035372,
  0.06402371823787689,
  -0.01535683311522007,
  0.037418439984321594,
  0.013272091746330261,
  -0.03784608095884323,
  0.021748512983322144,
  0.025856906548142433,
  0.01077498309314251,
  -0.0293696578592062,
  0.017059754580259323,
  -0.028254739940166473,
  -0.0027949283830821514,
  -0.024268532171845436,
  0.02617763541638851,
  -0.021504148840904236,
  -0.00120369007345289,
  0.01253899559378624,
  0.025795813649892807,
  0.007346232421696186,
  -0.00013053498696535826,
  0.032011859118938446,
  0.02220669947564602,
  -0.0029533840715885162,
  -0.02254270203411579,
  0.009507338516414165,
  -0.006926229689270258,
  0.03002638928592205,
  -0.030194390565156937,
  -0.027231460437178612,
  0.005475310608744621,
  -2.5221055693691596e-05,
  -0.019976865500211716,
  0.03192022070288658,
  0.005440946668386459,
  -0.05064471438527107,
  0.01062989141792059,
  0.0057540396228432655,
  -0.019365951418876648,
  -0.036807525902986526,
  0.023428525775671005,
  0.004749850835651159,
  0.06420698761940002,
  0.03314204886555672,
  0.025016900151968002,
  -0.03830426558852196,
  0.030744211748242378,
  0.03268386051058769,
  0.019717227667570114,
  0.009919704869389534,
  -0.023795073851943016,
  0.0018814221257343888,
  -0.0008905970607884228,
  -0.013974642381072044,
  -0.02947656810283661,
  -0.019610317423939705,
  0.030759485438466072,
  0.04423012211918831,
  0.013653912581503391,
  0.05986950546503067,
  0.028758743777871132,
  -0.046215590089559555,
  -0.0405646450817585,
  0.04508540406823158,
  -0.01788448728621006,
  -0.005971677601337433,
  0.03158421814441681,
  0.024558715522289276,
  0.04514649510383606,
  -0.015585925430059433,
  0.010797892697155476,
  -0.013088817708194256,
  -0.02125978283584118,
  -0.01785394176840782,
  0.009400428272783756,
  0.05095016956329346,
  0.02365761809051037,
  -0.00436039362102747,
  -0.004413848742842674,
  0.014486282132565975,
  -0.019961591809988022,
  0.01368445809930563,
  -0.04154210537672043,
  0.022955067455768585,
  -0.03143148869276047,
  0.036990802735090256,
  0.017273573204874992,
  0.030163845047354698,
  -0.012783360667526722,
  0.011592079885303974,
  0.04126719385385513,
  0.019365951418876648,
  0.029430748894810677,
  0.006311498116701841,
  -0.022695429623126984,
  -0.029461294412612915,
  0.03366132453083992,
  0.036440979689359665,
  0.06261861324310303,
  -0.028926745057106018,
  0.00029519523377530277,
  -0.028254739940166473,
  0.010683346539735794,
  -0.06261861324310303,
  -0.03888463228940964,
  0.003010657150298357,
  -0.027277279645204544,
  0.03360023349523544,
  -0.028270013630390167,
  -0.006139678880572319,
  0.007395869120955467,
  -0.012798633426427841,
  -0.03111075982451439,
  -0.07740271836519241,
  -0.02333688922226429,
  -0.0010022796923294663,
  -0.014929194003343582,
  0.031034396961331367,
  -0.04566577076911926,
  -0.00817860197275877,
  -0.006002223119139671,
  -0.06099969521164894,
  0.047712329775094986,
  -0.021381966769695282,
  0.022435791790485382,
  -0.02781182900071144,
  -0.01415791641920805,
  -0.053271640092134476,
  0.03500533103942871,
  -0.009621884673833847,
  0.012752815149724483,
  0.03192022070288658,
  0.010820802301168442,
  -0.008506967686116695,
  0.04157264903187752,
  -0.0008228238439187407,
  0.029965298250317574,
  0.031278762966394424,
  -0.04502430930733681,
  0.007327141705900431,
  0.08283984661102295,
  -0.012065538205206394,
  -0.046185046434402466,
  0.023764528334140778,
  -0.02755219116806984,
  0.03231731429696083,
  -0.03152312710881233,
  0.04532976821064949,
  0.02046559564769268,
  0.02177906036376953,
  0.03497478738427162,
  -0.03256167843937874,
  0.005406582728028297,
  -0.001721057342365384,
  -0.009598975069820881,
  -0.0013802822213619947,
  -0.007873144932091236,
  -0.04111446440219879,
  -0.049819979816675186,
  -0.005337854847311974,
  -0.052874546498060226,
  0.0321340411901474,
  -0.06536772102117538,
  -0.01777757704257965,
  0.02028232254087925,
  -0.03692970797419548,
  0.030728939920663834,
  0.04691814258694649,
  0.04090064764022827,
  0.07862454652786255,
  -0.021000145003199577,
  0.04383302852511406,
  -0.033019863069057465,
  0.02344379760324955,
  -0.039678819477558136,
  -0.014532100409269333,
  0.03888463228940964,
  -0.027888191863894463,
  -0.03277549892663956,
  -0.029278021305799484,
  -0.02678854949772358,
  0.002350107068195939,
  0.007048412226140499,
  0.021763786673545837,
  0.0056814937852323055,
  -0.025536175817251205,
  -0.011317169293761253,
  -0.03915954381227493,
  -0.0019358315039426088,
  0.012890270911157131,
  0.07563106715679169,
  -0.019763045012950897,
  0.0326533168554306,
  -0.014631373807787895,
  0.04765123873949051,
  -0.008743696846067905,
  0.0168612077832222,
  -0.022130334749817848,
  0.0005235717981122434,
  -0.014203734695911407,
  -0.008804787881672382,
  0.047345779836177826,
  -0.04606286436319351,
  0.07636416703462601,
  0.006853683851659298,
  -0.004558940418064594,
  -0.042550113052129745,
  0.0013182363472878933,
  -0.014509190805256367,
  -0.01838849112391472,
  0.07220995426177979,
  0.027872920036315918,
  0.016005929559469223,
  0.037571169435977936,
  -0.0247572623193264,
  0.03674643486738205,
  -0.014952103607356548,
  -0.005272945389151573,
  -0.011408805847167969,
  0.010904802940785885,
  0.0134324561804533,
  0.003944208845496178,
  0.003308477345854044,
  -0.0574258528649807,
  0.020221229642629623,
  0.016082292422652245,
  0.049483977258205414,
  -0.02747582644224167,
  0.013478274457156658,
  -0.05055307596921921,
  0.009621884673833847,
  -0.07703616470098495,
  0.03830426558852196,
  -0.026910731568932533,
  -0.027200914919376373,
  -0.0621604286134243,
  0.0008247329969890416,
  0.0038926631677895784,
  -0.0011865082196891308,
  -0.013638639822602272,
  -0.004830033518373966,
  -0.022771794348955154,
  -0.04746796563267708,
  -0.025749996304512024,
  0.03983154892921448,
  -0.028942018747329712,
  -0.014738284051418304,
  0.08662750571966171,
  0.02665109373629093,
  -0.031202398240566254,
  -0.04969779774546623,
  0.0012428268091753125,
  -0.01344772893935442,
  -0.04746796563267708,
  0.03347804769873619,
  -0.006460408214479685,
  -0.0035891158040612936,
  0.027796555310487747,
  0.0719044953584671,
  -0.01912158727645874,
  0.004509303718805313,
  -0.04459667205810547,
  0.01777757704257965,
  -0.003291295375674963,
  0.03237840533256531,
  -0.03769335150718689,
  -0.016601569950580597,
  0.038365356624126434,
  -0.05351600423455238,
  -0.0044291215017437935,
  -0.041022829711437225,
  -0.03769335150718689,
  -0.031462036073207855,
  0.0015578289749100804,
  -0.02995002456009388,
  -0.029934752732515335,
  -0.013478274457156658,
  0.04138937592506409,
  -0.0015463742893189192,
  -0.040045365691185,
  -0.011737171560525894,
  0.008652059361338615,
  0.03369186818599701,
  -0.0053454916924238205,
  -0.0200226828455925,
  0.031675856560468674,
  -0.047559600323438644,
  -0.027582736685872078,
  -0.008316057734191418,
  -0.011836444959044456,
  0.0010060978820547462,
  -0.02423798479139805,
  -0.007964782416820526,
  -0.02417689375579357,
  -0.029965298250317574,
  0.030286027118563652,
  0.012363358400762081,
  -0.03390568867325783,
  -0.018495401367545128,
  0.01077498309314251,
  -0.06946084648370743,
  0.015456106513738632,
  0.003623479511588812,
  -0.010293888859450817,
  -0.01991577446460724,
  -0.04193919897079468,
  0.022802339866757393,
  -0.030912213027477264,
  -0.0015406470047309995,
  -0.01588374562561512,
  -0.004948397632688284,
  -0.023321615532040596,
  0.037174075841903687,
  -0.008384785614907742,
  0.015563016757369041,
  0.0076860529370605946,
  0.03137039765715599,
  0.02104596421122551,
  -0.03097330406308174,
  -0.009423337876796722,
  0.015295742079615593,
  0.020664142444729805,
  -0.02235942706465721,
  -0.004639123100787401,
  0.023688163608312607,
  0.018128853291273117,
  0.0062160431407392025,
  0.02238997258245945,
  0.04010646045207977,
  0.01820521615445614,
  -0.019640862941741943,
  -0.002615472534671426,
  -0.014371735975146294,
  -0.03002638928592205,
  -0.011324805207550526,
  -0.017869213595986366,
  -0.008422967046499252,
  -0.028453286737203598,
  -0.04920906573534012,
  -0.011065167374908924,
  -0.009293518960475922,
  0.0020045593846589327,
  0.01201208308339119,
  0.061885517090559006,
  0.021947059780359268,
  0.027491098269820213,
  0.030835850164294243,
  0.013562275096774101,
  -0.04380248486995697,
  -0.00804878305643797,
  -0.024253258481621742,
  0.016739023849368095,
  0.005631857085973024,
  -0.021458329632878304,
  -0.018296852707862854,
  -0.016509931534528732,
  0.015288105234503746,
  -0.027323096990585327,
  0.00999606866389513,
  0.03111075982451439,
  -0.020694687962532043,
  -0.017243027687072754,
  -0.007850236259400845,
  -0.013913550414144993,
  -0.023825619369745255,
  0.008606241084635258,
  0.0376628041267395,
  0.0009535974822938442,
  -0.013989915139973164,
  0.019365951418876648,
  -0.05070580542087555,
  -0.004039664287120104,
  -0.02231360785663128,
  -0.013295001350343227,
  0.04502430930733681,
  -0.00016776252596173435,
  -0.004906397312879562,
  -0.01617392897605896,
  -0.003205385757610202,
  -0.020557232201099396,
  0.039678819477558136,
  0.014173189178109169,
  -0.0017010117881000042,
  0.006074769422411919,
  0.008590968325734138,
  -0.024085257202386856,
  0.01625029370188713,
  0.011263714171946049,
  0.036257706582546234,
  0.024405986070632935,
  -0.018984131515026093,
  0.0030889303889125586,
  -0.023428525775671005,
  0.027720190584659576,
  0.00665131863206625,
  -0.013875368982553482,
  0.011599716730415821,
  -0.005337854847311974,
  -0.012088446877896786,
  -0.0063954987563192844,
  -0.003409659955650568,
  0.05104180797934532,
  0.01550192479044199,
  0.046185046434402466,
  -0.026635820046067238,
  -0.008896425366401672,
  0.005941132083535194,
  -0.00557840196415782,
  -0.03732680156826973,
  0.022115061059594154,
  -0.012126629240810871,
  0.009385155513882637,
  0.013913550414144993,
  -0.03879299387335777,
  0.0350358784198761,
  -0.0410839207470417,
  0.017655394971370697,
  -0.026269271969795227,
  0.002092377981171012,
  0.03610497713088989,
  -0.04038136824965477,
  0.00588767696171999,
  0.019976865500211716,
  -0.006200769916176796,
  0.00041451421566307545,
  0.006265679839998484,
  -0.03295877203345299,
  0.0007459823973476887,
  -0.007403505500406027,
  -0.018953585997223854,
  -0.018785584717988968,
  0.018495401367545128,
  0.03747953101992607,
  0.028453286737203598,
  -0.021030690521001816,
  0.006838411092758179,
  -0.04035082459449768,
  -0.014142642728984356,
  -0.0052653090097010136,
  0.0238408911973238,
  -0.03521915152668953,
  0.0037322985008358955,
  0.006429862696677446,
  -0.001637056702747941,
  0.02489471808075905,
  0.014891011640429497,
  -0.015204104594886303,
  0.015135377645492554,
  0.00986624974757433,
  3.236528209527023e-05,
  0.00872078724205494,
  -0.0031576582696288824,
  0.010912438854575157,
  0.03323368355631828,
  -0.010553527623414993,
  -0.012477904558181763,
  -0.04322211816906929,
  -0.013806641101837158,
  -0.027216188609600067,
  -0.060358233749866486,
  -0.0012065537739545107,
  -0.029430748894810677,
  -0.007166776806116104,
  -0.014700101688504219,
  -0.010141161270439625,
  0.01497501228004694,
  0.0022718338295817375,
  -0.01115680392831564,
  -0.03708243742585182,
  -0.030958032235503197,
  -0.012180084362626076,
  0.012622996233403683,
  0.05238581448793411,
  0.0008738923934288323,
  0.01588374562561512,
  -0.04413848742842674,
  -0.012493177317082882,
  0.01046952698379755,
  0.006582590751349926,
  0.000852414988912642,
  0.007372959982603788,
  -0.008132783696055412,
  0.028117284178733826,
  0.013646275736391544,
  0.015899019315838814,
  -0.020129593089222908,
  0.02576526813209057,
  0.027384189888834953,
  -0.003566206432878971,
  -0.019686682149767876,
  -0.0658564567565918,
  -0.024069983512163162,
  0.02293979562819004,
  0.0031271125189960003,
  0.004639123100787401,
  -0.017029209062457085,
  0.019197950139641762,
  0.020694687962532043,
  -0.008751332759857178,
  0.01925904117524624,
  -0.03182858228683472,
  0.004375666379928589,
  -0.040045365691185,
  -0.0029839295893907547,
  0.002260379260405898,
  0.029675114899873734,
  0.029522385448217392,
  0.03445551171898842,
  -0.005517310928553343,
  0.018892494961619377,
  -0.0008299829787574708,
  0.002751019084826112,
  0.033783506602048874,
  -0.00999606866389513,
  -0.03787662461400032,
  -0.0065520452335476875,
  0.012913180515170097,
  -0.0247572623193264,
  0.04300829768180847,
  -0.01381427701562643,
  0.006636045873165131,
  0.013241546228528023,
  0.02620818093419075,
  0.026192907243967056,
  0.02707873284816742,
  -0.02399362064898014,
  0.0613662414252758,
  -0.013485911302268505,
  0.005284400191158056,
  -0.02083214372396469,
  -0.03250058740377426,
  0.02675800211727619,
  -0.034944240003824234,
  0.010530618019402027,
  0.002506653778254986,
  -0.05623456835746765,
  0.00042644611676223576,
  -0.0017458756919950247,
  0.023642344400286674,
  -0.029522385448217392,
  0.01872449368238449,
  -0.0006199815543368459,
  0.014898648485541344,
  -0.016998663544654846,
  0.011317169293761253,
  -0.025322357192635536,
  -0.03182858228683472,
  -0.014631373807787895,
  0.002437925897538662,
  -0.02336743474006653,
  -0.012829179875552654,
  -0.007330959662795067,
  -0.036868616938591,
  0.00703313946723938,
  0.014868102967739105,
  -0.006292406935244799,
  0.012027355842292309,
  0.0006481408490799367,
  -0.03613552078604698,
  0.0313398540019989,
  0.05012543871998787,
  -0.006823137868195772,
  -0.02141251228749752,
  0.0053454916924238205,
  0.04438285157084465,
  0.007258413825184107,
  -0.017136117443442345,
  0.025032171979546547,
  -0.03173694759607315,
  0.020801598206162453,
  0.017136117443442345,
  -0.0219928789883852,
  -0.007273686584085226,
  -0.03922063484787941,
  -0.013440093025565147,
  -0.01901467703282833,
  -0.0018146034562960267,
  0.01406627893447876,
  0.01177535392343998,
  -0.021076509729027748,
  -0.006819319911301136,
  -0.007995327934622765,
  0.020694687962532043,
  0.011706626042723656,
  -0.02497108094394207,
  0.030118025839328766,
  0.01767066679894924,
  0.0119204455986619,
  -0.03295877203345299,
  0.021504148840904236,
  0.0342416912317276,
  0.01268408726900816,
  -0.036990802735090256,
  -0.005349309649318457,
  0.015143013559281826,
  0.007143867667764425,
  0.02628454566001892,
  0.007556234020739794,
  0.007078958209604025,
  -0.0012084628688171506,
  -0.02104596421122551,
  -0.01886194758117199,
  0.024512896314263344,
  -0.010591709055006504,
  -0.01550192479044199,
  -0.028667107224464417,
  0.013585184700787067,
  0.043527573347091675,
  0.032836589962244034,
  0.02591799758374691,
  -0.024299077689647675,
  0.012279357761144638,
  0.017273573204874992,
  0.018602309748530388,
  -0.02238997258245945,
  0.034699875861406326,
  -0.003340932074934244,

cohere embeddings

In [ ]:
# create embeddings (cohere)
# (비용 발생 주의)
cohere_emb = create_embeddings(df.text.tolist(), 'cohere')

AttributeError: 'DataFrame' object has no attribute 'text'

In [ ]:
# df['cohere_emb'] = cohere_emb

e5 embeddings

In [ ]:
# load gpu if possible
device = "cuda" if torch.cuda.is_available() else "cpu"

model_id = "intfloat/e5-base-v2"

# init tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id).to(device)
model.eval()

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Cancellation requested; stopping current tasks.

KeyboardInterrupt:

In [ ]:
# def create_e5_emb(docs, model):
#     """
#     e5 embedding 모델을 활용하여 임베딩 벡터 생성
#     """
#     docs = [f"query: {d}" for d in docs]
#     # tokenize
#     tokens = tokenizer(
#         docs, padding=True, max_length=512, truncation=True, return_tensors="pt"
#     ).to(device)
#     with torch.no_grad():
#         out = model(**tokens)
#         last_hidden = out.last_hidden_state.masked_fill( # from last hidden state
#             ~tokens["attention_mask"][..., None].bool(), 0.0
#         )
#         # average out embeddings per token (non-padding)
#         doc_embeds = last_hidden.sum(dim=1) / tokens["attention_mask"].sum(dim=1)[..., None]
#     return doc_embeds.cpu().numpy()

긴 runtime 주의 (약 2시간)

In [ ]:
# data = df.text.tolist()
# batch_size = 128

# for i in tqdm(range(0, len(data), batch_size)):
#     i_end = min(len(data), i+batch_size)
#     data_batch = data[i:i_end]
#     # embed current batch
#     embed_batch = create_e5_emb(data_batch)
#     if i == 0:
#         emb3 = embed_batch.copy()
#     else:
#         emb3 = np.concatenate([emb3, embed_batch.copy()])

In [ ]:
# emb3 = [list(e) for e in emb3]
# df['e5_emb'] = emb3

In [ ]:
# df.to_csv("quora_dataset_emb.csv", index=False)

embedding이 이미 처리된 데이터 읽어오기

In [4]:
df = pd.read_csv("dataset/quora_dataset_emb.csv")
# str -> list 형태로 변환
import json
df['openai_emb'] = df['openai_emb'].apply(json.loads)
df['cohere_emb'] = df['cohere_emb'].apply(json.loads)
df['e5_emb'] = df['e5_emb'].apply(json.loads)
df['duplicated_questions'] = df['duplicated_questions'].apply(json.loads)

In [5]:
df.head()

,text,id,duplicated_questions,length,openai_emb,cohere_emb,e5_emb
0,Astrology: I am a Capricorn Sun Cap moon and c...,11,[12],1,"[-0.005765771958976984, -0.018585262820124626,...","[-0.05834961, -0.010795593, -0.04522705, 0.035...","[0.059878636, -0.15769655, -0.14131568, -0.546..."
1,"I'm a triple Capricorn (Sun, Moon and ascendan...",12,[11],1,"[0.026014558970928192, -0.014319832436740398, ...","[-0.022338867, -0.0063285828, -0.057128906, 0....","[0.08937627, -0.2954505, -0.33455396, -0.32940..."
2,How can I be a good geologist?,15,[16],1,"[0.005276682320982218, 0.004194203298538923, 0...","[-0.012535095, 0.005092621, -0.033233643, -0.0...","[0.0825816, -0.09264662, -0.78053623, -0.32416..."
3,What should I do to be a great geologist?,16,[15],1,"[0.015116829425096512, 0.0010464431252330542, ...","[-0.013465881, 0.0018148422, -0.052612305, 0.0...","[-0.1653303, 0.19044468, -0.8906647, -0.364357..."
4,How do I read and find my YouTube comments?,23,[24],1,"[0.03505030274391174, -0.0010134828044101596, ...","[-0.0047836304, 0.028137207, -0.037231445, -0....","[0.50644577, -0.62657785, -0.2523397, -0.17112..."

### 3. Test set 선별

테스팅을 위해 필요한 랜덤 질문들 선별

In [6]:
# now choose random 10 rows of answers
test_query = random.choices(df.id, k=1000)

In [7]:
test_query[:5]

[np.int64(4182),
 np.int64(5217),
 np.int64(5121),
 np.int64(5851),
 np.int64(5702)]

In [8]:
test = df.loc[df.id.isin(test_query)]

각 테스트 질문별로 가장 유사한 질문들 top-k개 retrieve

In [9]:
from sklearn.metrics.pairwise import cosine_similarity

def search_top_k(search_df, search_df_column, id, topk):
    """
    search_df : search를 할 대상 dataframe
    search_df_column : search를 위해 사용될 embedding column name
    id : test query id
    topk : 유사도 기반으로 top-k개 선별
    """
    query = search_df.loc[search_df['id']==id, search_df_column].values[0]
    query_reshaped = np.array(query).reshape(1, -1)
    
    search_df = search_df.loc[search_df['id']!=id]
    # cosine similarity in batch
    similarities = cosine_similarity(query_reshaped, np.vstack(search_df[search_df_column].values)).flatten()
    
    search_df['similarity'] = similarities
    
    # Get top-k indices
    # hence we sort the topk indices again to ensure they are truly the top-k
    topk_indices = np.argpartition(similarities, -topk)[-topk:]
    topk_indices_sorted = topk_indices[np.argsort(-similarities[topk_indices])]
    
    # Retrieve the top-k results
    search_result = search_df.iloc[topk_indices_sorted]
    
    return search_result

- 각 테스트 질문당 데이터 전체를 대상으로 cosine_similarity를 계산하고
- openai embedding, cohere embedding에 대해 각각 질문 k 개씩 진행
- search_result format :
```json
{
    'question id' : cosine_sim 기준 유사한 질문 top-k개를 담은 pd.DataFrame,
    'question id' : ...
}
```

In [10]:
# 각 질문들 중, test 질문과 동일한 질문이 가장 유사하게 도출될 것이기 때문에
# test 질문을 제외한 top-5
query_results_openai = { k:search_top_k(df, 'openai_emb', k, 5) for k in test.id }
query_results_cohere = { k:search_top_k(df, 'cohere_emb', k, 5) for k in test.id }
# query_results_e5 = { k:search_top_k(df, 'e5_emb', k, 5) for k in test.id }

테스트 결과 엿보기

In [12]:
test.loc[test.length==3].tail()

,text,id,duplicated_questions,length,openai_emb,cohere_emb,e5_emb
5102,How do I prepare for the IAS exam at home?,13689,"[13690, 14412, 77]",3,"[-0.026480073109269142, -0.0040580169297754765...","[-0.036315918, 0.037841797, -0.008079529, 0.00...","[-0.22943993, -0.31133857, -0.7906301, -0.5486..."
5265,How do I tell if a girl I sit next to likes me?,14160,"[10062, 14159, 10061]",3,"[-0.033233653753995895, -0.05941774323582649, ...","[-0.02444458, 0.020690918, -0.048980713, 0.043...","[-0.14724778, -0.9844855, -0.5622967, -0.37356..."
5345,What workout attire would guys wear in the sum...,14383,"[14382, 7092, 7091]",3,"[0.015372652560472488, 0.05050443112850189, -0...","[-0.041809082, -0.008651733, -0.10015869, 0.04...","[0.100323245, -0.7722157, -0.9635854, 0.348478..."
5404,How do I my increase memory power?,14637,"[14636, 10681, 10682]",3,"[0.022645525634288788, -0.005303962621837854, ...","[0.0047340393, 0.02658081, -0.052825928, -0.02...","[-0.31909862, -0.46033445, -0.46627238, -0.031..."
5419,Do you think there's life on other planets?,14686,"[12523, 12524, 14685]",3,"[0.01339676696807146, 0.008889188058674335, -0...","[-0.032592773, 0.010681152, -0.022476196, 0.04...","[-0.07575863, -0.05358007, -0.8569687, -0.0457..."

In [13]:
test.loc[test['id']==14182, 'text'].values

array([], dtype=object)

In [14]:
query_results_openai[14160]

,text,id,duplicated_questions,length,openai_emb,cohere_emb,e5_emb,similarity
3859,How do I know if this girl likes me?,10062,"[14160, 14159, 10061]",3,"[0.005086907651275396, -0.04189901426434517, 0...","[-0.054016113, 0.020217896, -0.054351807, 0.03...","[0.15249164, -0.9194247, -0.5637354, -0.653950...",0.716677
5264,I really like this girl. How can I tell if she...,14159,"[10062, 14160]",2,"[0.02182772010564804, -0.0494832806289196, 0.0...","[-0.035308838, 0.011474609, -0.06335449, 0.023...","[0.11682795, -1.0554899, -0.6295922, -0.749011...",0.671997
3858,How can a boy know if a girl likes him or not?,10061,"[10062, 14160]",2,"[0.014881503768265247, -0.0225174929946661, -0...","[-0.033721924, 0.013214111, -0.05218506, 0.026...","[0.05057525, -0.5991401, -0.77512205, -0.24307...",0.572684
1915,How do I tell if a guy likes me?,4994,"[2364, 4993, 2365]",3,"[-0.011051975190639496, -0.02304232493042946, ...","[-0.0023727417, 0.040924072, -0.052215576, 0.0...","[0.13690588, -0.6286884, -0.49419472, -0.29673...",0.560749
897,How do I know that a guy likes you?,2364,"[4993, 2365, 4994]",3,"[-0.007538170553743839, -0.012518931180238724,...","[-0.0055503845, 0.033416748, -0.046875, 0.0051...","[0.09061116, -0.58743984, -0.35238704, -0.2609...",0.524444

### 4. Scoring function 정의

- 각 질문별로 accuracy score 부여
    - Accuracy score : 현재 유사하다고 태그된 질문들 중 몇 개가 실제 유사한 질문들인가?

In [15]:
def score_accuracy(full_df, tmp_df, test_id):
    """
    각 테스트 질문과 유사하다고 판단된 질문들 중, 실제 duplicated_questions에 들어있는 질문들을 count
    """
    duplicated_questions = full_df.loc[full_df['id'] == test_id, 'duplicated_questions'].values[0]

    # 본인 ID는 제외
    filtered_df = tmp_df[tmp_df['id'] != test_id]
    # 현재 retrieve 해온 ID들이, 테스트 질문 내에 들어있는 아이디들인지 count
    match_count = filtered_df['id'].isin(duplicated_questions).sum()

    # Calculate the accuracy in terms of percentage
    if filtered_df.shape[0]<len(duplicated_questions):
        percentage = (match_count / filtered_df.shape[0])
    else:
        percentage = (match_count / len(duplicated_questions))
    return percentage

In [16]:
accuracy_openai = [score_accuracy(df, query_results_openai[i], i) for i in query_results_openai.keys()]
# accuracy_cohere = [score_accuracy(df, query_results_cohere[i], i) for i in query_results_cohere.keys()]
# accuracy_e5 = [score_accuracy(df, query_results_e5[i], i) for i in query_results_e5.keys()]

In [17]:
accuracy_cohere = [score_accuracy(df, query_results_cohere[i], i) for i in query_results_cohere.keys()]

In [18]:
accuracy_openai

[np.float64(1.0),
 np.float64(0.5),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(0.6),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(0.4),
 np.float64(0.6666666666666666),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(0.75),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6666666666666666),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(0.4),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6666666666666666),
 np.float64(0.6666666666666666),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.4),
 np.float64(0.4),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(0.5),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.2),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6666666666666666),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.4),
 np.float64(1.0),
 np.float64(0.3333333333333333),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(0.4),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6666666666666666),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6666666666666666),
 np.float64(0.0),
 np.float64(0.2),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.75),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.4),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6666666666666666),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.75),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.25),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.75),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.75),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.2),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.2),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.75),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.75),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(0.5),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.4),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.4),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6666666666666666),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6666666666666666),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.8),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(0.4),
 np.float64(0.2),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.4)]

In [19]:
np.mean(accuracy_openai)

np.float64(0.9536105032822756)

In [ ]:
# np.mean(accuracy_cohere)

In [ ]:
# np.mean(accuracy_e5)

오답 엿보기

In [20]:
indices = [[index,value] for index, value in enumerate(accuracy_openai) if value <= 0.5]

In [21]:
indices

[[1, np.float64(0.5)],
 [11, np.float64(0.4)],
 [19, np.float64(0.0)],
 [51, np.float64(0.0)],
 [103, np.float64(0.0)],
 [120, np.float64(0.4)],
 [138, np.float64(0.4)],
 [139, np.float64(0.4)],
 [185, np.float64(0.5)],
 [205, np.float64(0.2)],
 [292, np.float64(0.4)],
 [294, np.float64(0.3333333333333333)],
 [348, np.float64(0.0)],
 [353, np.float64(0.4)],
 [443, np.float64(0.0)],
 [444, np.float64(0.2)],
 [462, np.float64(0.4)],
 [521, np.float64(0.0)],
 [565, np.float64(0.25)],
 [572, np.float64(0.0)],
 [616, np.float64(0.0)],
 [658, np.float64(0.2)],
 [675, np.float64(0.2)],
 [731, np.float64(0.5)],
 [764, np.float64(0.4)],
 [797, np.float64(0.4)],
 [799, np.float64(0.0)],
 [875, np.float64(0.0)],
 [906, np.float64(0.4)],
 [907, np.float64(0.2)],
 [913, np.float64(0.4)]]

In [ ]:
list(query_results_openai.keys())[60]

817

In [85]:
test.loc[test['id']==985]

,text,id,duplicated_questions,length,openai_emb,cohere_emb,e5_emb
378,What are some tricks to study effectively?,985,[984],1,"[0.022660082206130028, -0.025483181700110435, ...","[0.012863159, 0.02041626, -0.017868042, 0.0209...","[0.2421261, -0.087377824, -0.7994292, -0.37665..."

In [86]:
test.loc[test['id']==984]

Empty DataFrame
Columns: [text, id, duplicated_questions, length, openai_emb, cohere_emb, e5_emb]
Index: []

In [87]:
query_results_openai[985]

,text,id,duplicated_questions,length,openai_emb,cohere_emb,e5_emb,similarity
2674,What are some good tips for self study?,7033,[7034],1,"[0.011717529967427254, -0.036956727504730225, ...","[-0.004623413, 0.0098724365, -0.028701782, 0.0...","[0.042563524, -0.11200364, -0.805879, -0.17195...",0.709618
2675,What are some tips for self study?,7034,[7033],1,"[0.013052663765847683, -0.036678362637758255, ...","[-0.0050735474, 0.015113831, -0.035949707, 0.0...","[0.0115949465, -0.0983381, -0.8623934, -0.2426...",0.696768
4327,What are the best ways to study/memorize things?,11331,[11332],1,"[-0.01611529476940632, -0.020404629409313202, ...","[-0.018630981, -0.0075263977, -0.024902344, -0...","[0.3084511, 0.2693039, -0.69890785, -0.1166682...",0.661062
1456,How do I concentrate better in my studies?,3902,[3903],1,"[0.008100658655166626, -0.02210518717765808, -...","[0.010749817, 0.043182373, -0.024032593, -0.00...","[0.48886126, -0.24943542, -0.675636, -0.476426...",0.646608
2961,How do I study well without getting distracted?,7803,[7802],1,"[0.0016504509840160608, -0.03981846570968628, ...","[0.041503906, 0.03475952, -0.02571106, -0.0210...","[0.45737946, -0.23788102, -0.9406135, -0.41269...",0.645310

#### 결론

- cohere, openai, e5 모두 굉장히 성능이 좋기 때문에 대부분의 task에 곧바로 활용해도 무방함.
- Local embedding 모델을 활용하고자 할 때 위와 같은 방법으로 classification 성능 & 자원 할당 체크 필요.
- 성능 평가 방법
    - 태깅된 데이터 셋 활용
    - 정성적 평가
        - 데이터 태깅을 할 노동력이 부족할 때
        - 태깅을 하기 애매한 분야 (정답이 없는 경우)

--END--