# Example 1: PDF 테이블 정보에 대한 Recursive Retrieval 전략
- 다수의 CSV 테이블 대상으로 검색 chunk와 답변 생성 chunk 분리해보기

In [1]:
# pip install llama-index-embeddings-openai llama-index-llms-openai camelot-py llama-index

In [2]:
# !apt-get install ghostscript
# !pip install ghostscript

In [3]:
import camelot

# https://en.wikipedia.org/wiki/The_World%27s_Billionaires
from llama_index.core import VectorStoreIndex
# from llama_index.core.query_engine import PandasQueryEngine
from llama_index.core.schema import IndexNode
from llama_index.llms.openai import OpenAI

from llama_index.readers.file import PyMuPDFReader
from typing import List

/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

In [4]:
from dotenv import load_dotenv
import os
import openai
load_dotenv()
openai.api_key = os.environ["OPENAI_API_KEY"]

In [5]:
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.llms.openai import OpenAI
from llama_index.core import Settings

# 추후 사용할 llm, 임베딩 모델 클래스 정의
Settings.llm = OpenAI(model="gpt-4o-mini", temperature=0)
Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-small", dimensions=512)

/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
# 파싱할 파일 경로 설정
file_path = "dataset/Billionaires.pdf"

In [7]:
# PDF파서 정의
reader = PyMuPDFReader()

In [8]:
# 업로드된 경로에서 로딩스테이지 진행한 후 다큐먼트 단위로 저장
docs = reader.load(file_path)

In [9]:
# 도큐먼트 정보 확인
docs

[Document(id_='28a24f0d-d7eb-45a7-b5ab-15d631cc3f97', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '1'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text_resource=MediaResource(embeddings=None, data=None, text="The World's Billionaires\nList of the world's billionaires, ranked in order of net worth\nThe net worth of the world's billionaires increased from\nless than $1 trillion in 2000 to over $16 trillion in 2025.\nPublication details\nPublisher\nWhale Media Investments\nForbes family\nPublication\nForbes\nFirst published\nMarch 1987[1]\nLatest publication\nApril 1, 2025\n2025 list details[2]\nWealthiest\nElon Musk\nNet worth (1st)\n\xa0US$342\xa0billion\nNumber of\nbillionaires\n\xa03,028 (from 2,781)\nTotal list net worth\nvalue\n\xa0US$16.1\xa0trillion (from US$14.2\ntrillion)\nNumber of women\n\xa0406\nNumber of men\n\xa02,622\nNew members to the\nlist\n\xa0247\nWorld’s Billionaires List The Richest In 2025 (https://www.\nforbes.com/billionaires/)\nThe World's Billionaires\nThe World's Billionaires is an annual\nranking of people who are billionaires, i.e.,\nthey are considered to have a net worth of\nUS$1 billion or more, by the American\nbusiness magazine Forbes. The list was first\npublished in March 1987.[1] The total net\nworth of each individual on the list is\nestimated and is cited in United States\ndollars, based on their documented assets\nand accounting for debt and other factors.\nRoyalty and dictators whose wealth comes\nfrom their positions are excluded from these\nlists.[3] This ranking is an index of the\nwealthiest \ndocumented \nindividuals,\nexcluding any ranking of those with wealth\nthat \nis \nnot \nable \nto \nbe \ncompletely\nascertained.[4]\nIn 2018, Amazon founder Jeff Bezos was\nranked at the top for the first time and\nbecame the first centibillionaire included in\nthe ranking,[5] surpassing Microsoft founder\nBill Gates, who had topped the list 18 of the\nprevious 24 years.[6] In 2022, after topping\nthe list for four years, Bezos was surpassed\nby Elon Musk.[7] In 2023, Musk was in turn\nsurpassed by French businessman Bernard\nArnault, after topping the list for just a year.\nArnault became the first French person to\ntop the list.[8] In 2025, Musk once again\nbecame the wealthiest man in the list after\nsurpassing Arnault.[2]\nEach year, Forbes employs a team of over 50\nreporters from a variety of countries to track the activity of the world's wealthiest individuals[9] and\nsometimes groups or families – who share wealth. Preliminary surveys are sent to those who may qualify\nfor the list. According to Forbes, they received three types of responses\xa0– some people try to inflate their\nwealth, others cooperate but leave out details, and some refuse to answer any questions.[10] Business\nMethodology\n", path=None, url=None, mimetype=None), image_resource=None, audio_resource=None, video_resource=None, text_template='{metadata_str}\n\n{content}'),
 Document(id_='7f04623d-9fa4-4286-94c4-e59349b20c46', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '2'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text_resource=MediaResource(embeddings=None, data=None, text='deals are then scrutinized and estimates of valuable assets\xa0– land, homes, vehicles, artwork, etc.\xa0– are\nmade. Interviews are conducted to vet the figures and improve the estimate of an individual\'s holdings.\nFinally, positions in a publicly traded stock are priced to market on a date roughly a month before\npublication. Privately held companies are priced by the prevailing price-to-sales or price-to-earnings\nratios. Known debt is subtracted from assets to get a final estimate of an individual\'s estimated worth in\nUnited States dollars. Since stock prices fluctuate rapidly, an individual\'s true wealth and ranking at the\ntime of publication may vary from their situation when the list was compiled.[9]\nWhen a living individual has dispersed his or her wealth to immediate family members it is included\nunder a single listing (as a single "family fortune") provided that individual (the grantor) is still living.\nHowever, if a deceased billionaire\'s fortune has been dispersed, it will not appear as a single listing, and\neach recipient will only appear if his or her own total net worth is over a $1 billion (his or her net worth\nwill not be combined with family members\').[9] Royal families and dictators that have their wealth\ncontingent on a position are always excluded from these lists.[11]\nThe rankings are published annually in March, so the net worths listed are snapshots taken at that time.\nThere are thousands of billionaires on the Forbes list; the excerpts below show only the wealthiest 10 for\neach year.\nLegend\nIcon\nDescription\nHas not changed from the previous ranking.\nHas increased from the previous ranking.\nHas decreased from the previous ranking.\nThe 39th annual Forbes list of the world\'s billionaires found a record 3,028 billionaires with a total net\nworth of $16.1 trillion. This represents an increase of 247 members and $1.9 trillion compared to 2024.\nThis year also marked the first time Bill Gates dropped out of the top 10 richest people, which he had\nbeen part of for 33 years since the 6th annual Forbes list of the world\'s billionaires in 1992.\nAnnual rankings\n2025\n', path=None, url=None, mimetype=None), image_resource=None, audio_resource=None, video_resource=None, text_template='{metadata_str}\n\n{content}'),
 Document(id_='8df7c097-123b-49e6-957b-483a42e326e5', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '3'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text_resource=MediaResource(embeddings=None, data=None, text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of\nwealth\n1 \nElon Musk\n$342\xa0billion\xa0\n53\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla and SpaceX\n2 \nMark Zuckerberg[nb 1]\n$216\xa0billion\xa0\n40\n\xa0United\nStates\nMeta Platforms\n3 \nJeff Bezos\n$215\xa0billion\xa0\n61\n\xa0United\nStates\nAmazon\n4 \nLarry Ellison\n$192\xa0billion\xa0\n80\n\xa0United\nStates\nOracle Corporation\n5 \nBernard Arnault &\nfamily\n$178\xa0billion\xa0\n76\n\xa0France\nLVMH\n6 \nWarren Buffett\n$154\xa0billion\xa0\n94\n\xa0United\nStates\nBerkshire Hathaway\n7 \nLarry Page\n$144\xa0billion\xa0\n52\n\xa0United\nStates\nGoogle\n8 \nSergey Brin\n$138\xa0billion\xa0\n51\n\xa0United\nStates\nGoogle\n9 \nAmancio Ortega\n$124\xa0billion\xa0\n89\n\xa0Spain\nInditex, Zara\n10\nSteve Ballmer\n$118\xa0billion\xa0\n69\n\xa0United\nStates\nMicrosoft\nThe 38th annual Forbes list of the world's billionaires found a record 2,781 billionaires with a total net\nwealth of $14.2 trillion. This is an increase of 141 members and $2 trillion from 2023, which held the\nprevious record for the highest net worth gain on the list, surpassing the $900 billion record set in 2022.\nTwo-thirds of the list members are wealthier compared to the previous year, including Mark Zuckerberg,\nwhose net worth increased by $112.6 billion.\n2024\n", path=None, url=None, mimetype=None), image_resource=None, audio_resource=None, video_resource=None, text_template='{metadata_str}\n\n{content}'),
 Document(id_='62f2b8c8-0893-4082-b48a-6fdc7c5b7f1c', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '4'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text_resource=MediaResource(embeddings=None, data=None, text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of\nwealth\n1 \nBernard Arnault &\nfamily\n$233\xa0billion\xa0\n75\n\xa0France\nLVMH\n2 \nElon Musk\n$195\xa0billion\xa0\n52\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla, SpaceX\n3 \nJeff Bezos\n$194\xa0billion\xa0\n60\n\xa0United\nStates\nAmazon\n4 \nMark Zuckerberg\n$177\xa0billion\xa0\n39\n\xa0United\nStates\nMeta Platforms\n5 \nLarry Ellison\n$141\xa0billion\xa0\n79\n\xa0United\nStates\nOracle Corporation\n6 \nWarren Buffett\n$133\xa0billion\xa0\n93\n\xa0United\nStates\nBerkshire Hathaway\n7 \nBill Gates\n$128\xa0billion\xa0\n68\n\xa0United\nStates\nMicrosoft\n8 \nSteve Ballmer\n$121\xa0billion\xa0\n68\n\xa0United\nStates\nMicrosoft\n9 \nMukesh Ambani\n$116\xa0billion \n66\n\xa0India\nReliance Industries\n10\nLarry Page\n$114\xa0billion\xa0\n51\n\xa0United\nStates\nGoogle\nIn the 37th annual Forbes list of the world's billionaires, the list included 2,640 billionaires with a total\nnet wealth of $12.2 trillion, down 28 members and $500 billion from 2022. Over half of the list is less\nwealthy compared to the previous year, including Elon Musk, who fell from No. 1 to No. 2.[8] The list\nalso marks for the first time a French citizen was in the top position as well as a non-American for the\nfirst time since 2013 when the Mexican Carlos Slim Helu was the world's richest person. The list, like in\n2022, counted 15 under 30 billionaires with the richest of them being Red Bull heir Mark Mateschitz with\na net worth of $34.7 billion. The youngest of the lot were Clemente Del Vecchio, heir to the Luxottica\nfortune shared with his six siblings and stepmother, and Kim Jung-yang, whose fortune lies in Japanese-\nSouth Korean gaming giant Nexon, both under-20s.[13]\n2023\n", path=None, url=None, mimetype=None), image_resource=None, audio_resource=None, video_resource=None, text_template='{metadata_str}\n\n{content}'),
 Document(id_='7fd561af-c543-4e34-a8a5-d764faa13abc', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '5'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text_resource=MediaResource(embeddings=None, data=None, text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of wealth\n1 \nBernard Arnault &\nfamily\n$211\xa0billion\xa0\n74\n\xa0France\nLVMH\n2 \nElon Musk\n$180\xa0billion\xa0\n51\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla, SpaceX\n3 \nJeff Bezos\n$114\xa0billion\xa0\n59\n\xa0United\nStates\nAmazon\n4 \nLarry Ellison\n$107\xa0billion\xa0\n78\n\xa0United\nStates\nOracle Corporation\n5 \nWarren Buffett\n$106\xa0billion\xa0\n92\n\xa0United\nStates\nBerkshire Hathaway\n6 \nBill Gates\n$104\xa0billion\xa0\n67\n\xa0United\nStates\nMicrosoft\n7 \nMichael Bloomberg\n$94.5\xa0billion\xa0\n81\n\xa0United\nStates\nBloomberg L.P.\n8 \nCarlos Slim & family\n$93\xa0billion\xa0\n83\n\xa0Mexico\nTelmex, América Móvil, Grupo\nCarso\n9 \nMukesh Ambani\n$83.4\xa0billion \n65\n\xa0India\nReliance Industries\n10\nSteve Ballmer\n$80.7\xa0billion\xa0\n67\n\xa0United\nStates\nMicrosoft\nIn the 36th annual Forbes list of the world's billionaires, the list included 2,668 billionaires with a total\nnet wealth of $12.7 trillion, down 97 members from 2021.[7]\n2022\n", path=None, url=None, mimetype=None), image_resource=None, audio_resource=None, video_resource=None, text_template='{metadata_str}\n\n{content}'),
 Document(id_='9c175949-f4b9-4989-83df-f357e2d7f89f', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '6'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text_resource=MediaResource(embeddings=None, data=None, text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of\nwealth\n1 \nElon Musk\n$219\xa0billion\xa0\n50\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla, SpaceX\n2 \nJeff Bezos\n$177\xa0billion\xa0\n58\n\xa0United\nStates\nAmazon\n3 \nBernard Arnault &\nfamily\n$158\xa0billion\xa0\n73\n\xa0France\nLVMH\n4 \nBill Gates\n$129\xa0billion\xa0\n66\n\xa0United\nStates\nMicrosoft\n5 \nWarren Buffett\n$118\xa0billion\xa0\n91\n\xa0United\nStates\nBerkshire Hathaway\n6 \nLarry Page\n$111\xa0billion\xa0\n49\n\xa0United\nStates\nGoogle\n7 \nSergey Brin\n$107\xa0billion\xa0\n48\n\xa0United\nStates\nGoogle\n8 \nLarry Ellison\n$106\xa0billion\xa0\n77\n\xa0United\nStates\nOracle Corporation\n9 \nSteve Ballmer\n$91.4\xa0billion\xa0\n66\n\xa0United\nStates\nMicrosoft\n10\nMukesh Ambani\n$90.7\xa0billion \n64\n\xa0India\nReliance Industries\nIn the 35th annual Forbes list of the world's billionaires, the list included 2,755 billionaires with a total\nnet wealth of $13.1 trillion, up 660 members from 2020; 86% of these billionaires had more wealth than\nthey possessed last year.[14][15]\nNo.\nName\nNet worth (USD)\nAge\nNationality\nSource(s) of wealth\n1 \nJeff Bezos\n$177\xa0billion\xa0\n57\n\xa0United States\nAmazon\n2 \nElon Musk\n$151\xa0billion\xa0\n49\n\xa0South Africa\n\xa0Canada\n\xa0United States\nTesla, SpaceX\n3 \nBernard Arnault & family\n$150\xa0billion\xa0\n72\n\xa0France\nLVMH\n4 \nBill Gates\n$124\xa0billion\xa0\n65\n\xa0United States\nMicrosoft\n5 \nMark Zuckerberg\n$97\xa0billion\xa0\n36\n\xa0United States\nMeta Platforms\n6 \nWarren Buffett\n$96\xa0billion\xa0\n90\n\xa0United States\nBerkshire Hathaway\n7 \nLarry Ellison\n$93\xa0billion\xa0\n76\n\xa0United States\nOracle Corporation\n8 \nLarry Page\n$91.5\xa0billion\xa0\n48\n\xa0United States\nGoogle\n9 \nSergey Brin\n$89\xa0billion\xa0\n47\n\xa0United States\nGoogle\n10 \nMukesh Ambani\n$84.5\xa0billion \n63\n\xa0India\nReliance Industries\n2021\n", path=None, url=None, mimetype=None), image_resource=None, audio_resource=None, video_resource=None, text_template='{metadata_str}\n\n{content}'),
 Document(id_='9e84b4fd-d228-4268-986e-7a67335a1a1b', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '7'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text_resource=MediaResource(embeddings=None, data=None, text="In the 34th annual Forbes list of the world's billionaires, the list included 2,095 billionaires with a total\nnet wealth of $8 trillion, down 58 members and $700 billion from 2019; 51% of these billionaires had\nless wealth than they possessed last year.[16] The list was finalized as of 18 March, thus was already\npartially influenced by the COVID-19 pandemic.[16]\nNo.\nName\nNet worth (USD)\nAge\nNationality\nSource(s) of wealth\n1 \nJeff Bezos\n$113\xa0billion\xa0\n56\n\xa0United States\nAmazon\n2 \nBill Gates\n$98\xa0billion\xa0\n64\n\xa0United States\nMicrosoft\n3 \nBernard Arnault & family\n$76\xa0billion\xa0\n71\n\xa0France\nLVMH\n4 \nWarren Buffett\n$67.5\xa0billion\xa0\n89\n\xa0United States\nBerkshire Hathaway\n5 \nLarry Ellison\n$59\xa0billion\xa0\n75\n\xa0United States\nOracle Corporation\n6 \nAmancio Ortega\n$55.1\xa0billion\xa0\n84\n\xa0Spain\nInditex, Zara\n7 \nMark Zuckerberg\n$54.7\xa0billion\xa0\n35\n\xa0United States\nFacebook, Inc.\n8 \nJim Walton\n$54.6\xa0billion\xa0\n71\n\xa0United States\nWalmart\n9 \nAlice Walton\n$54.4\xa0billion\xa0\n70\n\xa0United States\nWalmart\n10 \nS. Robson Walton\n$54.1\xa0billion\xa0\n77\n\xa0United States\nWalmart\nIn the 33rd annual Forbes list of the world's billionaires, the list included 2,153 billionaires with a total\nnet wealth of $8.7 trillion, down 55 members and $400 billion from 2018.[17] The U.S. continued to have\nthe most billionaires in the world, with a record of 609, while China dropped to 324 (when not including\nHong Kong, Macau and Taiwan).[17]\nNo.\nName\nNet worth (USD)\nAge\nNationality\nSource(s) of wealth\n1 \nJeff Bezos\n$131\xa0billion\xa0\n55\n\xa0United States\nAmazon\n2 \nBill Gates\n$96.5\xa0billion\xa0\n63\n\xa0United States\nMicrosoft\n3 \nWarren Buffett\n$82.5\xa0billion\xa0\n88\n\xa0United States\nBerkshire Hathaway\n4 \nBernard Arnault\n$76\xa0billion\xa0\n70\n\xa0France\nLVMH\n5 \nCarlos Slim\n$64\xa0billion\xa0\n79\n\xa0Mexico\nAmérica Móvil, Grupo Carso\n6 \nAmancio Ortega\n$62.7\xa0billion\xa0\n82\n\xa0Spain\nInditex, Zara\n7 \nLarry Ellison\n$62.5\xa0billion\xa0\n74\n\xa0United States\nOracle Corporation\n8 \nMark Zuckerberg\n$62.3\xa0billion\xa0\n34\n\xa0United States\nFacebook, Inc.\n9 \nMichael Bloomberg\n$55.5\xa0billion\xa0\n77\n\xa0United States\nBloomberg L.P.\n10 \nLarry Page\n$50.8\xa0billion\xa0\n45\n\xa0United States\nGoogle\n2020\n2019\n", path=None, url=None, mimetype=None), image_resource=None, audio_resource=None, video_resource=None, text_template='{metadata_str}\n\n{content}'),

In [10]:
from llama_index.core import Settings
#노드변환 및 파싱
doc_nodes = Settings.node_parser.get_nodes_from_documents(docs)

In [11]:
doc_nodes

[TextNode(id_='31d8f268-e35f-42f8-b676-bae5aa29ff6d', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '1'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='28a24f0d-d7eb-45a7-b5ab-15d631cc3f97', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '1'}, hash='290cadf340323aac5ec3699cb86bcaa607560cedb39511ae0774637bb885f91e')}, metadata_template='{key}: {value}', metadata_separator='\n', text="The World's Billionaires\nList of the world's billionaires, ranked in order of net worth\nThe net worth of the world's billionaires increased from\nless than $1 trillion in 2000 to over $16 trillion in 2025.\nPublication details\nPublisher\nWhale Media Investments\nForbes family\nPublication\nForbes\nFirst published\nMarch 1987[1]\nLatest publication\nApril 1, 2025\n2025 list details[2]\nWealthiest\nElon Musk\nNet worth (1st)\n\xa0US$342\xa0billion\nNumber of\nbillionaires\n\xa03,028 (from 2,781)\nTotal list net worth\nvalue\n\xa0US$16.1\xa0trillion (from US$14.2\ntrillion)\nNumber of women\n\xa0406\nNumber of men\n\xa02,622\nNew members to the\nlist\n\xa0247\nWorld’s Billionaires List The Richest In 2025 (https://www.\nforbes.com/billionaires/)\nThe World's Billionaires\nThe World's Billionaires is an annual\nranking of people who are billionaires, i.e.,\nthey are considered to have a net worth of\nUS$1 billion or more, by the American\nbusiness magazine Forbes. The list was first\npublished in March 1987.[1] The total net\nworth of each individual on the list is\nestimated and is cited in United States\ndollars, based on their documented assets\nand accounting for debt and other factors.\nRoyalty and dictators whose wealth comes\nfrom their positions are excluded from these\nlists.[3] This ranking is an index of the\nwealthiest \ndocumented \nindividuals,\nexcluding any ranking of those with wealth\nthat \nis \nnot \nable \nto \nbe \ncompletely\nascertained.[4]\nIn 2018, Amazon founder Jeff Bezos was\nranked at the top for the first time and\nbecame the first centibillionaire included in\nthe ranking,[5] surpassing Microsoft founder\nBill Gates, who had topped the list 18 of the\nprevious 24 years.[6] In 2022, after topping\nthe list for four years, Bezos was surpassed\nby Elon Musk.[7] In 2023, Musk was in turn\nsurpassed by French businessman Bernard\nArnault, after topping the list for just a year.\nArnault became the first French person to\ntop the list.[8] In 2025, Musk once again\nbecame the wealthiest man in the list after\nsurpassing Arnault.[2]\nEach year, Forbes employs a team of over 50\nreporters from a variety of countries to track the activity of the world's wealthiest individuals[9] and\nsometimes groups or families – who share wealth. Preliminary surveys are sent to those who may qualify\nfor the list. According to Forbes, they received three types of responses\xa0– some people try to inflate their\nwealth, others cooperate but leave out details, and some refuse to answer any questions.[10] Business\nMethodology", mimetype='text/plain', start_char_idx=0, end_char_idx=2468, text_template='{metadata_str}\n\n{content}'),
 TextNode(id_='e275f9ea-7fc9-4359-bf69-6d2fbb4e9813', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '2'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='7f04623d-9fa4-4286-94c4-e59349b20c46', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '2'}, hash='dd11b645d8595fd746b7544aca1a83baeaddb4e01d564943c555ae8615027c1a')}, metadata_template='{key}: {value}', metadata_separator='\n', text='deals are then scrutinized and estimates of valuable assets\xa0– land, homes, vehicles, artwork, etc.\xa0– are\nmade. Interviews are conducted to vet the figures and improve the estimate of an individual\'s holdings.\nFinally, positions in a publicly traded stock are priced to market on a date roughly a month before\npublication. Privately held companies are priced by the prevailing price-to-sales or price-to-earnings\nratios. Known debt is subtracted from assets to get a final estimate of an individual\'s estimated worth in\nUnited States dollars. Since stock prices fluctuate rapidly, an individual\'s true wealth and ranking at the\ntime of publication may vary from their situation when the list was compiled.[9]\nWhen a living individual has dispersed his or her wealth to immediate family members it is included\nunder a single listing (as a single "family fortune") provided that individual (the grantor) is still living.\nHowever, if a deceased billionaire\'s fortune has been dispersed, it will not appear as a single listing, and\neach recipient will only appear if his or her own total net worth is over a $1 billion (his or her net worth\nwill not be combined with family members\').[9] Royal families and dictators that have their wealth\ncontingent on a position are always excluded from these lists.[11]\nThe rankings are published annually in March, so the net worths listed are snapshots taken at that time.\nThere are thousands of billionaires on the Forbes list; the excerpts below show only the wealthiest 10 for\neach year.\nLegend\nIcon\nDescription\nHas not changed from the previous ranking.\nHas increased from the previous ranking.\nHas decreased from the previous ranking.\nThe 39th annual Forbes list of the world\'s billionaires found a record 3,028 billionaires with a total net\nworth of $16.1 trillion. This represents an increase of 247 members and $1.9 trillion compared to 2024.\nThis year also marked the first time Bill Gates dropped out of the top 10 richest people, which he had\nbeen part of for 33 years since the 6th annual Forbes list of the world\'s billionaires in 1992.\nAnnual rankings\n2025', mimetype='text/plain', start_char_idx=0, end_char_idx=2104, text_template='{metadata_str}\n\n{content}'),
 TextNode(id_='7e2764eb-72f9-4f38-9ea1-0c5f964921f6', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '3'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='8df7c097-123b-49e6-957b-483a42e326e5', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '3'}, hash='d7e5aed581354f96fa96407e37a359ff918458fb49693db4694f0f822a790a1c')}, metadata_template='{key}: {value}', metadata_separator='\n', text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of\nwealth\n1 \nElon Musk\n$342\xa0billion\xa0\n53\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla and SpaceX\n2 \nMark Zuckerberg[nb 1]\n$216\xa0billion\xa0\n40\n\xa0United\nStates\nMeta Platforms\n3 \nJeff Bezos\n$215\xa0billion\xa0\n61\n\xa0United\nStates\nAmazon\n4 \nLarry Ellison\n$192\xa0billion\xa0\n80\n\xa0United\nStates\nOracle Corporation\n5 \nBernard Arnault &\nfamily\n$178\xa0billion\xa0\n76\n\xa0France\nLVMH\n6 \nWarren Buffett\n$154\xa0billion\xa0\n94\n\xa0United\nStates\nBerkshire Hathaway\n7 \nLarry Page\n$144\xa0billion\xa0\n52\n\xa0United\nStates\nGoogle\n8 \nSergey Brin\n$138\xa0billion\xa0\n51\n\xa0United\nStates\nGoogle\n9 \nAmancio Ortega\n$124\xa0billion\xa0\n89\n\xa0Spain\nInditex, Zara\n10\nSteve Ballmer\n$118\xa0billion\xa0\n69\n\xa0United\nStates\nMicrosoft\nThe 38th annual Forbes list of the world's billionaires found a record 2,781 billionaires with a total net\nwealth of $14.2 trillion. This is an increase of 141 members and $2 trillion from 2023, which held the\nprevious record for the highest net worth gain on the list, surpassing the $900 billion record set in 2022.\nTwo-thirds of the list members are wealthier compared to the previous year, including Mark Zuckerberg,\nwhose net worth increased by $112.6 billion.\n2024", mimetype='text/plain', start_char_idx=0, end_char_idx=1165, text_template='{metadata_str}\n\n{content}'),
 TextNode(id_='6b377d92-c09a-41a3-96fe-8dc5b928b9ce', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '4'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='62f2b8c8-0893-4082-b48a-6fdc7c5b7f1c', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '4'}, hash='d44df096d348872a3f1cea025a1e524c576f4fc93ba0cf998ed0050c0cf8bf37')}, metadata_template='{key}: {value}', metadata_separator='\n', text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of\nwealth\n1 \nBernard Arnault &\nfamily\n$233\xa0billion\xa0\n75\n\xa0France\nLVMH\n2 \nElon Musk\n$195\xa0billion\xa0\n52\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla, SpaceX\n3 \nJeff Bezos\n$194\xa0billion\xa0\n60\n\xa0United\nStates\nAmazon\n4 \nMark Zuckerberg\n$177\xa0billion\xa0\n39\n\xa0United\nStates\nMeta Platforms\n5 \nLarry Ellison\n$141\xa0billion\xa0\n79\n\xa0United\nStates\nOracle Corporation\n6 \nWarren Buffett\n$133\xa0billion\xa0\n93\n\xa0United\nStates\nBerkshire Hathaway\n7 \nBill Gates\n$128\xa0billion\xa0\n68\n\xa0United\nStates\nMicrosoft\n8 \nSteve Ballmer\n$121\xa0billion\xa0\n68\n\xa0United\nStates\nMicrosoft\n9 \nMukesh Ambani\n$116\xa0billion \n66\n\xa0India\nReliance Industries\n10\nLarry Page\n$114\xa0billion\xa0\n51\n\xa0United\nStates\nGoogle\nIn the 37th annual Forbes list of the world's billionaires, the list included 2,640 billionaires with a total\nnet wealth of $12.2 trillion, down 28 members and $500 billion from 2022. Over half of the list is less\nwealthy compared to the previous year, including Elon Musk, who fell from No. 1 to No. 2.[8] The list\nalso marks for the first time a French citizen was in the top position as well as a non-American for the\nfirst time since 2013 when the Mexican Carlos Slim Helu was the world's richest person. The list, like in\n2022, counted 15 under 30 billionaires with the richest of them being Red Bull heir Mark Mateschitz with\na net worth of $34.7 billion. The youngest of the lot were Clemente Del Vecchio, heir to the Luxottica\nfortune shared with his six siblings and stepmother, and Kim Jung-yang, whose fortune lies in Japanese-\nSouth Korean gaming giant Nexon, both under-20s.[13]\n2023", mimetype='text/plain', start_char_idx=0, end_char_idx=1589, text_template='{metadata_str}\n\n{content}'),
 TextNode(id_='be3ba10c-30cb-40d8-85b8-9c7dcdc93473', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '5'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='7fd561af-c543-4e34-a8a5-d764faa13abc', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '5'}, hash='4630b374abc6bc8d7377965be975640d67c4d7b19a3f614ed0e2ba91417c7229')}, metadata_template='{key}: {value}', metadata_separator='\n', text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of wealth\n1 \nBernard Arnault &\nfamily\n$211\xa0billion\xa0\n74\n\xa0France\nLVMH\n2 \nElon Musk\n$180\xa0billion\xa0\n51\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla, SpaceX\n3 \nJeff Bezos\n$114\xa0billion\xa0\n59\n\xa0United\nStates\nAmazon\n4 \nLarry Ellison\n$107\xa0billion\xa0\n78\n\xa0United\nStates\nOracle Corporation\n5 \nWarren Buffett\n$106\xa0billion\xa0\n92\n\xa0United\nStates\nBerkshire Hathaway\n6 \nBill Gates\n$104\xa0billion\xa0\n67\n\xa0United\nStates\nMicrosoft\n7 \nMichael Bloomberg\n$94.5\xa0billion\xa0\n81\n\xa0United\nStates\nBloomberg L.P.\n8 \nCarlos Slim & family\n$93\xa0billion\xa0\n83\n\xa0Mexico\nTelmex, América Móvil, Grupo\nCarso\n9 \nMukesh Ambani\n$83.4\xa0billion \n65\n\xa0India\nReliance Industries\n10\nSteve Ballmer\n$80.7\xa0billion\xa0\n67\n\xa0United\nStates\nMicrosoft\nIn the 36th annual Forbes list of the world's billionaires, the list included 2,668 billionaires with a total\nnet wealth of $12.7 trillion, down 97 members from 2021.[7]\n2022", mimetype='text/plain', start_char_idx=0, end_char_idx=902, text_template='{metadata_str}\n\n{content}'),
 TextNode(id_='241fc8a7-3619-456d-b963-dbe2a7d1ca38', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '6'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='9c175949-f4b9-4989-83df-f357e2d7f89f', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '6'}, hash='cd1fffa1dcbaf05a6279fd85864981d5ca47facbc86142a693d7cf080cde09e9')}, metadata_template='{key}: {value}', metadata_separator='\n', text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of\nwealth\n1 \nElon Musk\n$219\xa0billion\xa0\n50\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla, SpaceX\n2 \nJeff Bezos\n$177\xa0billion\xa0\n58\n\xa0United\nStates\nAmazon\n3 \nBernard Arnault &\nfamily\n$158\xa0billion\xa0\n73\n\xa0France\nLVMH\n4 \nBill Gates\n$129\xa0billion\xa0\n66\n\xa0United\nStates\nMicrosoft\n5 \nWarren Buffett\n$118\xa0billion\xa0\n91\n\xa0United\nStates\nBerkshire Hathaway\n6 \nLarry Page\n$111\xa0billion\xa0\n49\n\xa0United\nStates\nGoogle\n7 \nSergey Brin\n$107\xa0billion\xa0\n48\n\xa0United\nStates\nGoogle\n8 \nLarry Ellison\n$106\xa0billion\xa0\n77\n\xa0United\nStates\nOracle Corporation\n9 \nSteve Ballmer\n$91.4\xa0billion\xa0\n66\n\xa0United\nStates\nMicrosoft\n10\nMukesh Ambani\n$90.7\xa0billion \n64\n\xa0India\nReliance Industries\nIn the 35th annual Forbes list of the world's billionaires, the list included 2,755 billionaires with a total\nnet wealth of $13.1 trillion, up 660 members from 2020; 86% of these billionaires had more wealth than\nthey possessed last year.[14][15]\nNo.\nName\nNet worth (USD)\nAge\nNationality\nSource(s) of wealth\n1 \nJeff Bezos\n$177\xa0billion\xa0\n57\n\xa0United States\nAmazon\n2 \nElon Musk\n$151\xa0billion\xa0\n49\n\xa0South Africa\n\xa0Canada\n\xa0United States\nTesla, SpaceX\n3 \nBernard Arnault & family\n$150\xa0billion\xa0\n72\n\xa0France\nLVMH\n4 \nBill Gates\n$124\xa0billion\xa0\n65\n\xa0United States\nMicrosoft\n5 \nMark Zuckerberg\n$97\xa0billion\xa0\n36\n\xa0United States\nMeta Platforms\n6 \nWarren Buffett\n$96\xa0billion\xa0\n90\n\xa0United States\nBerkshire Hathaway\n7 \nLarry Ellison\n$93\xa0billion\xa0\n76\n\xa0United States\nOracle Corporation\n8 \nLarry Page\n$91.5\xa0billion\xa0\n48\n\xa0United States\nGoogle\n9 \nSergey Brin\n$89\xa0billion\xa0\n47\n\xa0United States\nGoogle\n10 \nMukesh Ambani\n$84.5\xa0billion \n63\n\xa0India\nReliance Industries\n2021", mimetype='text/plain', start_char_idx=0, end_char_idx=1613, text_template='{metadata_str}\n\n{content}'),
 TextNode(id_='c6ee8819-9538-4ce9-8979-fee3f780adb4', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '7'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='9e84b4fd-d228-4268-986e-7a67335a1a1b', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '7'}, hash='a3f510fea14a9161d2311ca81d05a2ad58b633f9612150e41af4e890766f5c95')}, metadata_template='{key}: {value}', metadata_separator='\n', text="In the 34th annual Forbes list of the world's billionaires, the list included 2,095 billionaires with a total\nnet wealth of $8 trillion, down 58 members and $700 billion from 2019; 51% of these billionaires had\nless wealth than they possessed last year.[16] The list was finalized as of 18 March, thus was already\npartially influenced by the COVID-19 pandemic.[16]\nNo.\nName\nNet worth (USD)\nAge\nNationality\nSource(s) of wealth\n1 \nJeff Bezos\n$113\xa0billion\xa0\n56\n\xa0United States\nAmazon\n2 \nBill Gates\n$98\xa0billion\xa0\n64\n\xa0United States\nMicrosoft\n3 \nBernard Arnault & family\n$76\xa0billion\xa0\n71\n\xa0France\nLVMH\n4 \nWarren Buffett\n$67.5\xa0billion\xa0\n89\n\xa0United States\nBerkshire Hathaway\n5 \nLarry Ellison\n$59\xa0billion\xa0\n75\n\xa0United States\nOracle Corporation\n6 \nAmancio Ortega\n$55.1\xa0billion\xa0\n84\n\xa0Spain\nInditex, Zara\n7 \nMark Zuckerberg\n$54.7\xa0billion\xa0\n35\n\xa0United States\nFacebook, Inc.\n8 \nJim Walton\n$54.6\xa0billion\xa0\n71\n\xa0United States\nWalmart\n9 \nAlice Walton\n$54.4\xa0billion\xa0\n70\n\xa0United States\nWalmart\n10 \nS. Robson Walton\n$54.1\xa0billion\xa0\n77\n\xa0United States\nWalmart\nIn the 33rd annual Forbes list of the world's billionaires, the list included 2,153 billionaires with a total\nnet wealth of $8.7 trillion, down 55 members and $400 billion from 2018.[17] The U.S. continued to have\nthe most billionaires in the world, with a record of 609, while China dropped to 324 (when not including\nHong Kong, Macau and Taiwan).[17]\nNo.\nName\nNet worth (USD)\nAge\nNationality\nSource(s) of wealth\n1 \nJeff Bezos\n$131\xa0billion\xa0\n55\n\xa0United States\nAmazon\n2 \nBill Gates\n$96.5\xa0billion\xa0\n63\n\xa0United States\nMicrosoft\n3 \nWarren Buffett\n$82.5\xa0billion\xa0\n88\n\xa0United States\nBerkshire Hathaway\n4 \nBernard Arnault\n$76\xa0billion\xa0\n70\n\xa0France\nLVMH\n5 \nCarlos Slim\n$64\xa0billion\xa0\n79\n\xa0Mexico\nAmérica Móvil, Grupo Carso\n6 \nAmancio Ortega\n$62.7\xa0billion\xa0\n82\n\xa0Spain\nInditex, Zara\n7 \nLarry Ellison\n$62.5\xa0billion\xa0\n74\n\xa0United States\nOracle Corporation\n8 \nMark Zuckerberg\n$62.3\xa0billion\xa0\n34\n\xa0United States\nFacebook, Inc.\n9 \nMichael Bloomberg\n$55.5\xa0billion\xa0\n77\n\xa0United States\nBloomberg L.P.\n10 \nLarry Page\n$50.8\xa0billion\xa0\n45\n\xa0United States\nGoogle\n2020\n2019", mimetype='text/plain', start_char_idx=0, end_char_idx=2060, text_template='{metadata_str}\n\n{content}'),

In [12]:
vector_index0 = VectorStoreIndex(doc_nodes)
vector_query_engine0 = vector_index0.as_query_engine()

2026-02-28 08:45:03,088 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

In [13]:
vector_index0

In [14]:
response = vector_query_engine0.query(
    "How many billionaires were there in 2009?"
)

2026-02-28 08:45:05,394 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 08:45:06,776 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

In [15]:
print(response.source_nodes[0].node.get_content())

No.
Name
Net worth
(USD)
Age
Nationality
Source(s) of wealth
1
Carlos Slim
$74.0 billion
71
 Mexico
América Móvil, Grupo Carso
2
Bill Gates
$56.0 billion
55
 United
States
Microsoft
3
Warren Buffett
$50.0 billion
80
 United
States
Berkshire Hathaway
4
Bernard Arnault
$41.0 billion
62
 France
LVMH Moët Hennessy • Louis
Vuitton
5
Larry Ellison
$39.5 billion
66
 United
States
Oracle Corporation
6
Lakshmi Mittal
$31.1 billion
60
 India
Arcelor Mittal
7
Amancio Ortega
$31.0 billion
74
 Spain
Inditex Group
8
Eike Batista
$30.0 billion
53
 Brazil
EBX Group
9
Mukesh Ambani
$27.0 billion
54
 India
Reliance Industries
10
Christy Walton &
family
$26.5 billion
62
 United
States
Walmart
Slim narrowly eclipsed Gates to top the billionaire list for the first time. Slim saw his estimated worth
surge $18.5 billion to $53.5 billion as shares of America Movil rose 35 percent. Gates' estimated wealth
rose $13 billion to $53 billion, placing him second. Warren Buffett was third with $47 billion.[42] Christy
Walton was the highest-ranking woman, placing 12th overall, with an inherited fortune of $22.5
billion.[43] At age 25, Mark Zuckerberg continued to be the world's youngest self-made billionaire.[10]
American Isaac Perlmutter was among the newcomers with an estimated fortune of $4 billion largely
acquired in his sale of Marvel Entertainment to Disney.[42]
A total of 1,011 people made the 2010 list. The United States accounted for 403 billionaires, followed by
China with 89 and Russia with 62.[43] It was the first time China, while including Hong Kong, placed
second.[42] A total of 55 countries were represented on the 2010 list, including Finland and Pakistan
which claimed their first billionaires.[43] Eighty-nine women made the list, but only 14 of them were self-
made.[43] The combined net worth of the list was $3.6 trillion, up 50 percent from 2009's $2.4 trillion,
while the average net worth was $3.5 billion.[10]
The 2010 list featured 164 re-entries and 97 true newcomers.[10] Asia accounted for more than 100 of the
new entrants. Overall, just 12 percent of the list lost wealth since 2009, and 30 people fell off the list. 13
others died.[42] Of the 89 women, 12 were newcomers in 2010. Steve Forbes said the growing number of
billionaires was a clear sign that the world's economy was recovering from the Great Recession.[10]
In June 2010, Gates and Buffett announced the Giving Pledge, a promise to give the majority of their
wealth to philanthropic causes. As of 2017, the pledge had 158 signatories, but some of the signatories
have since died. Most of the signers of the pledge are billionaires, and their pledges total over $365
billion.[44]
2010

In [16]:
print(str(response))

The information provided does not specify the number of billionaires in 2009.

In [17]:
response = vector_query_engine0.query(
    "What's the net worth of the second richest billionaire in 2023?"
)
print(str(response))

2026-02-28 08:45:06,911 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 08:45:08,915 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

The net worth of the second richest billionaire in 2023 is $216 billion.

In [18]:
response

Response(response='The net worth of the second richest billionaire in 2023 is $216 billion.', source_nodes=[NodeWithScore(node=TextNode(id_='6b377d92-c09a-41a3-96fe-8dc5b928b9ce', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '4'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='62f2b8c8-0893-4082-b48a-6fdc7c5b7f1c', node_type='4', metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '4'}, hash='d44df096d348872a3f1cea025a1e524c576f4fc93ba0cf998ed0050c0cf8bf37')}, metadata_template='{key}: {value}', metadata_separator='\n', text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of\nwealth\n1 \nBernard Arnault &\nfamily\n$233\xa0billion\xa0\n75\n\xa0France\nLVMH\n2 \nElon Musk\n$195\xa0billion\xa0\n52\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla, SpaceX\n3 \nJeff Bezos\n$194\xa0billion\xa0\n60\n\xa0United\nStates\nAmazon\n4 \nMark Zuckerberg\n$177\xa0billion\xa0\n39\n\xa0United\nStates\nMeta Platforms\n5 \nLarry Ellison\n$141\xa0billion\xa0\n79\n\xa0United\nStates\nOracle Corporation\n6 \nWarren Buffett\n$133\xa0billion\xa0\n93\n\xa0United\nStates\nBerkshire Hathaway\n7 \nBill Gates\n$128\xa0billion\xa0\n68\n\xa0United\nStates\nMicrosoft\n8 \nSteve Ballmer\n$121\xa0billion\xa0\n68\n\xa0United\nStates\nMicrosoft\n9 \nMukesh Ambani\n$116\xa0billion \n66\n\xa0India\nReliance Industries\n10\nLarry Page\n$114\xa0billion\xa0\n51\n\xa0United\nStates\nGoogle\nIn the 37th annual Forbes list of the world's billionaires, the list included 2,640 billionaires with a total\nnet wealth of $12.2 trillion, down 28 members and $500 billion from 2022. Over half of the list is less\nwealthy compared to the previous year, including Elon Musk, who fell from No. 1 to No. 2.[8] The list\nalso marks for the first time a French citizen was in the top position as well as a non-American for the\nfirst time since 2013 when the Mexican Carlos Slim Helu was the world's richest person. The list, like in\n2022, counted 15 under 30 billionaires with the richest of them being Red Bull heir Mark Mateschitz with\na net worth of $34.7 billion. The youngest of the lot were Clemente Del Vecchio, heir to the Luxottica\nfortune shared with his six siblings and stepmother, and Kim Jung-yang, whose fortune lies in Japanese-\nSouth Korean gaming giant Nexon, both under-20s.[13]\n2023", mimetype='text/plain', start_char_idx=0, end_char_idx=1589, text_template='{metadata_str}\n\n{content}'), score=0.7118977830674788), NodeWithScore(node=TextNode(id_='7e2764eb-72f9-4f38-9ea1-0c5f964921f6', embedding=None, metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '3'}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='8df7c097-123b-49e6-957b-483a42e326e5', node_type='4', metadata={'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '3'}, hash='d7e5aed581354f96fa96407e37a359ff918458fb49693db4694f0f822a790a1c')}, metadata_template='{key}: {value}', metadata_separator='\n', text="No.\nName\nNet worth\n(USD)\nAge\nNationality\nPrimary source(s) of\nwealth\n1 \nElon Musk\n$342\xa0billion\xa0\n53\n\xa0South Africa\n\xa0Canada\n\xa0United\nStates\nTesla and SpaceX\n2 \nMark Zuckerberg[nb 1]\n$216\xa0billion\xa0\n40\n\xa0United\nStates\nMeta Platforms\n3 \nJeff Bezos\n$215\xa0billion\xa0\n61\n\xa0United\nStates\nAmazon\n4 \nLarry Ellison\n$192\xa0billion\xa0\n80\n\xa0United\nStates\nOracle Corporation\n5 \nBernard Arnault &\nfamily\n$178\xa0billion\xa0\n76\n\xa0France\nLVMH\n6 \nWarren Buffett\n$154\xa0billion\xa0\n94\n\xa0United\nStates\nBerkshire Hathaway\n7 \nLarry Page\n$144\xa0billion\xa0\n52\n\xa0United\nStates\nGoogle\n8 \nSergey Brin\n$138\xa0billion\xa0\n51\n\xa0United\nStates\nGoogle\n9 \nAmancio Ortega\n$124\xa0billion\xa0\n89\n\xa0Spain\nInditex, Zara\n10\nSteve Ballmer\n$118\xa0billion\xa0\n69\n\xa0United\nStates\nMicrosoft\nThe 38th annual Forbes list of the world's billionaires found a record 2,781 billionaires with a total net\nwealth of $14.2 trillion. This is an increase of 141 members and $2 trillion from 2023, which held the\nprevious record for the highest net worth gain on the list, surpassing the $900 billion record set in 2022.\nTwo-thirds of the list members are wealthier compared to the previous year, including Mark Zuckerberg,\nwhose net worth increased by $112.6 billion.\n2024", mimetype='text/plain', start_char_idx=0, end_char_idx=1165, text_template='{metadata_str}\n\n{content}'), score=0.6833912190436464)], metadata={'6b377d92-c09a-41a3-96fe-8dc5b928b9ce': {'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '4'}, '7e2764eb-72f9-4f38-9ea1-0c5f964921f6': {'total_pages': 35, 'file_path': 'dataset/Billionaires.pdf', 'source': '3'}})

In [19]:
print(response.source_nodes[0].node.get_content())

No.
Name
Net worth
(USD)
Age
Nationality
Primary source(s) of
wealth
1
Bernard Arnault &
family
$233 billion
75
 France
LVMH
2
Elon Musk
$195 billion
52
 South Africa
 Canada
 United
States
Tesla, SpaceX
3
Jeff Bezos
$194 billion
60
 United
States
Amazon
4
Mark Zuckerberg
$177 billion
39
 United
States
Meta Platforms
5
Larry Ellison
$141 billion
79
 United
States
Oracle Corporation
6
Warren Buffett
$133 billion
93
 United
States
Berkshire Hathaway
7
Bill Gates
$128 billion
68
 United
States
Microsoft
8
Steve Ballmer
$121 billion
68
 United
States
Microsoft
9
Mukesh Ambani
$116 billion
66
 India
Reliance Industries
10
Larry Page
$114 billion
51
 United
States
Google
In the 37th annual Forbes list of the world's billionaires, the list included 2,640 billionaires with a total
net wealth of $12.2 trillion, down 28 members and $500 billion from 2022. Over half of the list is less
wealthy compared to the previous year, including Elon Musk, who fell from No. 1 to No. 2.[8] The list
also marks for the first time a French citizen was in the top position as well as a non-American for the
first time since 2013 when the Mexican Carlos Slim Helu was the world's richest person. The list, like in
2022, counted 15 under 30 billionaires with the richest of them being Red Bull heir Mark Mateschitz with
a net worth of $34.7 billion. The youngest of the lot were Clemente Del Vecchio, heir to the Luxottica
fortune shared with his six siblings and stepmother, and Kim Jung-yang, whose fortune lies in Japanese-
South Korean gaming giant Nexon, both under-20s.[13]
2023

- 기본적인 PDF파싱모듈로는 테이블 등 Text-Only 가 아닌 문서에 대한 정보 해석력이 떨어지는 것을 확인
- Table정보를 따로 추출하여 답하는 방식은 어떨지?

In [54]:
def normalize_columns(df):
    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.replace("\n", " ")
        .str.replace(r"\s+", " ", regex=True)
        .str.lower()
    )
    return df

In [55]:
def get_tables(path: str, pages: List[int]):
    table_dfs = []

    for page in pages:
        tables = camelot.read_pdf(path, pages=str(page))

        for table in tables:
            df = table.df.copy()

            # 첫 행을 header로 쓰되, 비정상일 수 있음을 전제로
            header = df.iloc[0]
            df = df.iloc[1:].reset_index(drop=True)
            df.columns = header

            # 🔴 핵심: 컬럼 정규화
            df = normalize_columns(df)

            table_dfs.append(df)

    return table_dfs

In [56]:
table_dfs = get_tables(file_path, pages=[3,4,24])

KeyError: 'year'

In [58]:
#파싱된 테이블 개수확인
len(table_dfs)

4

In [59]:
#파싱 결과 확인
table_dfs[0]

,no.,name,net worth (usd),age,nationality,primary source(s) of wealth
0,1,Elon Musk,$342 billion,53,South Africa\n Canada\n United\nStates,Tesla and SpaceX
1,2,Mark Zuckerberg[nb 1],$216 billion,40,United\nStates,Meta Platforms
...,...,...,...,...,...,...
8,9,Amancio Ortega,$124 billion,89,Spain,"Inditex, Zara"
9,10,Steve Ballmer,$118 billion,69,United\nStates,Microsoft

In [24]:
#파싱 결과 확인
table_dfs[1]

,No.,Name,Net worth\n(USD),Age,Nationality,Primary source(s) of\nwealth
0,1,Bernard Arnault &\nfamily,$233 billion,75,France,LVMH
1,2,Elon Musk,$195 billion,52,South Africa\n Canada\n United\nStates,"Tesla, SpaceX"
2,3,Jeff Bezos,$194 billion,60,United\nStates,Amazon
3,4,Mark Zuckerberg,$177 billion,39,United\nStates,Meta Platforms
4,5,Larry Ellison,$141 billion,79,United\nStates,Oracle Corporation
5,6,Warren Buffett,$133 billion,93,United\nStates,Berkshire Hathaway
6,7,Bill Gates,$128 billion,68,United\nStates,Microsoft
7,8,Steve Ballmer,$121 billion,68,United\nStates,Microsoft
8,9,Mukesh Ambani,$116 billion,66,India,Reliance Industries
9,10,Larry Page,$114 billion,51,United\nStates,Google

In [25]:
#파싱 결과 확인
table_dfs[-1]

,No.[50],Name,Net worth (USD),Nationality,Source(s) of wealth
0,1,Walton family,$18.5 billion,United States,Wal-Mart
1,2,Taikichiro Mori,$15.0 billion,Japan,Mori Building Company
2,3,Yoshiaki Tsutsumi,$14.0 billion,Japan,Seibu Corporation
3,4,du Pont family,$10.0 billion,United States,DuPont
4,5,Hans and Gad Rausing,$9.0 billion,Sweden,Tetra Pak
5,6,Kitaro Watanabe,$7.7 billion,Japan,Azabu Building
6,7,Paul Reichmann & brothers,$7.1 billion,Canada,Olympia & York
7,8,Kenneth Thomson,$6.8 billion,Canada,Thomson Corporation
8,9,Kenkichi Nakajima,$6.1 billion,Japan,Heiwa Corporation
9,10,Shin Kyuk-ho,$6.0 billion,South Korea,Lotte Corporation

이제 테이블을 다 파싱해왔는데,
이것들을 기반으로 질문에 바로 답할수 있도록 만들려면 만들수도 있겠지만,
테이블이 지금과 다르게 수천 수만개일때, 모든 유저 쿼리에 대해 수만개의 테이블을 매번 조회하는 것은 실용성 없는 Naive한 접근방식(자원은 무한하지 않다).

그렇기 때문에,
1. 사용자의 질문과 관련된 테이블을 먼저 찾고
2. 찾은 테이블을 기준으로 사용자의 질문에 답할 수 있는 정보를 발췌하여 답해보자.

일단은 각 테이블별로 답해주는 담당 라마인덱스 쿼리엔진을 만들어주자.

In [26]:
from llama_index.experimental.query_engine import PandasQueryEngine

llm = OpenAI(model="gpt-4o-mini", temperature=0)

df_query_engines = [
    PandasQueryEngine(table_df, llm=llm) for table_df in table_dfs
]

In [65]:
# 상응하는 테이블 지정해서 답변 요구
response = df_query_engines[0].query(
    "What's the net worth of the second richest billionaire in 2023?"
)
print(response)

2026-02-28 10:23:20,206 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
There was an error running the output as Python code. Error message: could not convert string to float: '342 billion'

Traceback (most recent call last):
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/llama_index/experimental/query_engine/pandas/output_parser.py", line 62, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/llama_index/experimental/exec_utils.py", line 259, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6643, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 430, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 758, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 133, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '342 billion'

In [28]:
# 상응하는 테이블 지정해서 답변 요구
response = df_query_engines[1].query(
    "What's the net worth of the second richest billionaire in 2022?"
)
print(str(response))

2026-02-28 08:45:17,428 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
There was an error running the output as Python code. Error message: index 0 is out of bounds for axis 0 with size 0

Traceback (most recent call last):
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/llama_index/experimental/query_engine/pandas/output_parser.py", line 62, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/llama_index/experimental/exec_utils.py", line 259, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
IndexError: index 0 is out of bounds for axis 0 with size 0

In [29]:
len(df_query_engines)

4

In [30]:
response = df_query_engines[3].query(
    "How many billionaires were there in 2009?"
)
print(str(response))

2026-02-28 08:45:18,931 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
10

질문별로 담당하는 쿼리엔진을 부여하는 것으로 heuristic하게 서칭 스페이스를 줄이고 시작할 수 있는 것 확인

In [ ]:
# 쿼리엔진 요약문 생성 (엔진 개수와 항상 일치)
summaries = [
    f"This node provides information for extracted billionaire table #{idx}."
    for idx in range(len(df_query_engines))
]

#생성된 요약문 별 노드단위 생성
df_nodes = [
    IndexNode(text=summary, index_id=f"pandas{idx}") for idx, summary in enumerate(summaries)
]

#요약노드 <-> 쿼리엔진 매핑
df_id_query_engine_mapping = {
    f"pandas{idx}": df_query_engine
    for idx, df_query_engine in enumerate(df_query_engines)
}

assert len(df_nodes) == len(df_id_query_engine_mapping), (
    len(df_nodes), len(df_id_query_engine_mapping)
)

In [32]:
#생성된 노드 확인
df_nodes[0]

IndexNode(id_='675c1d2a-9293-495d-b48c-0754016d9930', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='This node provides information for extracted billionaire table #0.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', index_id='pandas0', obj=None)

In [33]:
#상위레벨 벡터스토어인덱스 정의
vector_index = VectorStoreIndex(df_nodes)
vector_retriever = vector_index.as_retriever(similarity_top_k=1)

2026-02-28 08:45:19,740 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

In [34]:
from llama_index.core.retrievers import RecursiveRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core import get_response_synthesizer

recursive_retriever = RecursiveRetriever(
    "vector",
    retriever_dict={"vector": vector_retriever},
    query_engine_dict=df_id_query_engine_mapping,
    verbose=True,
)

response_synthesizer = get_response_synthesizer(response_mode="compact")

query_engine = RetrieverQueryEngine.from_args(
    recursive_retriever, response_synthesizer=response_synthesizer
)

In [35]:
response = query_engine.query(
    "What's the net worth of the second richest billionaire in 2023?"
)

2026-02-28 08:45:19,897 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

Retrieving with query id None: What's the net worth of the second richest billionaire in 2023?
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
Retrieved node with id, entering: pandas2
Retrieving with query id pandas2: What's the net worth of the second richest billionaire in 2023?

2026-02-28 08:45:21,417 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Traceback (most recent call last):
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/llama_index/experimental/query_engine/pandas/output_parser.py", line 62, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/llama_index/experimental/exec_utils.py", line 259, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6643, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 430, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 758, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 133, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '$23.8'

Got response: There was an error running the output as Python code. Error message: could not convert string to float: '$23.8'

2026-02-28 08:45:22,961 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

In [36]:
response.source_nodes[0].node.get_content()

"Query: What's the net worth of the second richest billionaire in 2023?\nResponse: There was an error running the output as Python code. Error message: could not convert string to float: '$23.8'"

In [37]:
str(response)

'The net worth of the second richest billionaire in 2023 is $23.8 billion.'

In [38]:
response = query_engine.query("How many billionaires were there in 2009?")

2026-02-28 08:45:23,123 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

Retrieving with query id None: How many billionaires were there in 2009?
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
Retrieved node with id, entering: pandas1
Retrieving with query id pandas1: How many billionaires were there in 2009?

2026-02-28 08:45:24,387 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Traceback (most recent call last):
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Year'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/llama_index/experimental/query_engine/pandas/output_parser.py", line 62, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/llama_index/experimental/exec_utils.py", line 259, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Year'

Got response: There was an error running the output as Python code. Error message: 'Year'

2026-02-28 08:45:25,140 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

In [39]:
str(response)

'There was an error in retrieving the information regarding the number of billionaires in 2009.'

- 서머리 텍스트로 recursive retriever 모듈로 하여금 우리가 찾고자 하는 문서를 자동으로 판별해서 해당 쿼리엔진을 기반으로만 답하게 하는 것이 가능한 것 확인

- 파인콘 DB에 있는 데이터를 연계시켜서도 가능할까?

In [40]:
!pip install -U llama-index-vector-stores-pinecone pinecone datasets

Requirement already satisfied: llama-index-vector-stores-pinecone in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (0.7.1)
Requirement already satisfied: pinecone in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (7.3.0)
Collecting pinecone
  Using cached pinecone-8.1.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: datasets in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (4.6.0)
Collecting datasets
  Downloading datasets-4.6.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: llama-index-core<0.15,>=0.13.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-vector-stores-pinecone) (0.14.15)
Requirement already satisfied: certifi>=2019.11.17 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pinecone) (2026.1.4)
Requirement already satisfied: pinecone-plugin-assistant<2.0.0,>=1.6.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pinecone) (1.8.0)
Requirement already satisfied: pinecone-plugin-interface<0.0.8,>=0.0.7 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pinecone) (0.0.7)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pinecone) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=3.7.4 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pinecone) (4.15.0)
Requirement already satisfied: urllib3>=1.26.5 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pinecone) (2.6.3)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (3.13.3)
Requirement already satisfied: aiosqlite in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.22.1)
Requirement already satisfied: banks<3,>=2.3.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.4.1)
Requirement already satisfied: dataclasses-json in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.2.18)
Requirement already satisfied: dirtyjson<2,>=1.0.8 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.0.8)
Requirement already satisfied: filetype<2,>=1.2.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2025.10.0)
Requirement already satisfied: httpx in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.28.1)
Requirement already satisfied: llama-index-workflows!=2.9.0,<3,>=2 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.14.2)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (3.6.1)
Requirement already satisfied: nltk>3.8.1 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (3.9.3)
Requirement already satisfied: numpy in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.4.2)
Requirement already satisfied: pillow>=9.0.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (12.1.1)
Requirement already satisfied: platformdirs in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (4.7.0)
Requirement already satisfied: pydantic>=2.8.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.12.5)
Requirement already satisfied: pyyaml>=6.0.1 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.32.5)
Requirement already satisfied: setuptools>=80.9.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (82.0.0)
Requirement already satisfied: sqlalchemy>=1.4.49 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.0.47)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (9.1.4)
Requirement already satisfied: tiktoken>=0.7.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.12.0)
Requirement already satisfied: tinytag>=2.2.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.2.0)
Requirement already satisfied: tqdm<5,>=4.66.1 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (4.67.3)
Requirement already satisfied: typing-inspect>=0.8.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.9.0)
Requirement already satisfied: wrapt in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.17.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.22.0)
Requirement already satisfied: griffe in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.0.0)
Requirement already satisfied: jinja2 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (3.1.6)
Requirement already satisfied: llama-index-instrumentation>=0.1.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from llama-index-workflows!=2.9.0,<3,>=2->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.4.2)
Requirement already satisfied: packaging<25.0,>=24.2 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pinecone-plugin-assistant<2.0.0,>=1.6.0->pinecone) (24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from requests>=2.31.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from requests>=2.31.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (3.7)
Requirement already satisfied: filelock in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from datasets) (3.21.2)
Requirement already satisfied: pyarrow>=21.0.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from datasets) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from datasets) (2.2.3)
Requirement already satisfied: xxhash in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from datasets) (0.70.18)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from datasets) (1.4.1)
Requirement already satisfied: anyio in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from httpx->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (4.12.1)
Requirement already satisfied: httpcore==1.* in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from httpx->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from httpcore==1.*->httpx->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.2.0)
Requirement already satisfied: shellingham in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: typer-slim in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.23.1)
Requirement already satisfied: click in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from nltk>3.8.1->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (8.3.1)
Requirement already satisfied: joblib in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from nltk>3.8.1->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from nltk>3.8.1->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2026.1.15)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pydantic>=2.8.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pydantic>=2.8.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pydantic>=2.8.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.4.2)
Requirement already satisfied: six>=1.5 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from python-dateutil>=2.5.3->pinecone) (1.17.0)
Requirement already satisfied: greenlet>=1 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (3.3.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from typing-inspect>=0.8.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (1.1.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from dataclasses-json->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (3.26.2)
Requirement already satisfied: griffecli==2.0.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from griffe->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.0.0)
Requirement already satisfied: griffelib==2.0.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from griffe->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (2.0.0)
Requirement already satisfied: colorama>=0.4 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from griffecli==2.0.0->griffe->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from jinja2->banks<3,>=2.3.0->llama-index-core<0.15,>=0.13.0->llama-index-vector-stores-pinecone) (3.0.3)
Requirement already satisfied: pytz>=2020.1 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: typer>=0.23.1 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.23.1)
Requirement already satisfied: rich>=10.11.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from typer>=0.23.1->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from typer>=0.23.1->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from rich>=10.11.0->typer>=0.23.1->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from rich>=10.11.0->typer>=0.23.1->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/igyeongseob/Develop/ai/RAG/vectorDB/vector/venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.23.1->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Downloading datasets-4.6.1-py3-none-any.whl (520 kB)
Installing collected packages: datasets
  Attempting uninstall: datasets
    Found existing installation: datasets 4.6.0
    Uninstalling datasets-4.6.0:
      Successfully uninstalled datasets-4.6.0
Successfully installed datasets-4.6.1

In [41]:
import os
import re
from time import sleep

from pinecone import Pinecone, ServerlessSpec

from llama_index.core import (
    Settings,
    Document,
    VectorStoreIndex,
    StorageContext,
    get_response_synthesizer,
)
from llama_index.core.node_parser import TokenTextSplitter
from llama_index.core.schema import TextNode, IndexNode, MetadataMode
from llama_index.core.retrievers import RecursiveRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.tools import QueryEngineTool, ToolMetadata
from llama_index.core.agent import AgentWorkflow
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.llms.openai import OpenAI
from llama_index.vector_stores.pinecone import PineconeVectorStore

In [42]:
from dotenv import load_dotenv

load_dotenv()
pinecone_api_key = os.environ["PINECONE_API_KEY"]
# openai_api_key = os.environ["OPENAI_API_KEY"]

embed_model = OpenAIEmbedding(model="text-embedding-3-small", dimensions=512)
llm = OpenAI(model="gpt-4o-mini", temperature=0)

Settings.embed_model = embed_model
Settings.llm = llm

In [43]:
from datasets import load_dataset

FAST_DEV_MODE = True
DEV_SAMPLE_SIZE = 300
FULL_SAMPLE_EXPR = "train[:1000]"

split_expr = f"train[:{DEV_SAMPLE_SIZE}]" if FAST_DEV_MODE else FULL_SAMPLE_EXPR
dataset = load_dataset("lcw99/wikipedia-korean-20221001", split=split_expr)
data = dataset.to_pandas()[["id", "text", "title"]].drop_duplicates(subset="text", keep="first")
print(f"Loaded rows: {len(data)} (split={split_expr})")

2026-02-28 08:45:37,516 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/lcw99/wikipedia-korean-20221001/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/datasets/lcw99/wikipedia-korean-20221001/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"

2026-02-28 08:45:37,527 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lcw99/wikipedia-korean-20221001/49af0d4be8266217cb60bbc2bdb8e0ca0929b250/README.md "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lcw99/wikipedia-korean-20221001/49af0d4be8266217cb60bbc2bdb8e0ca0929b250/README.md "HTTP/1.1 200 OK"

2026-02-28 08:45:37,728 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/lcw99/wikipedia-korean-20221001/resolve/49af0d4be8266217cb60bbc2bdb8e0ca0929b250/wikipedia-korean-20221001.py "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/datasets/lcw99/wikipedia-korean-20221001/resolve/49af0d4be8266217cb60bbc2bdb8e0ca0929b250/wikipedia-korean-20221001.py "HTTP/1.1 404 Not Found"

2026-02-28 08:45:38,401 - INFO - HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lcw99/wikipedia-korean-20221001/lcw99/wikipedia-korean-20221001.py "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lcw99/wikipedia-korean-20221001/lcw99/wikipedia-korean-20221001.py "HTTP/1.1 404 Not Found"

2026-02-28 08:45:38,722 - INFO - HTTP Request: GET https://huggingface.co/api/datasets/lcw99/wikipedia-korean-20221001/revision/49af0d4be8266217cb60bbc2bdb8e0ca0929b250 "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/datasets/lcw99/wikipedia-korean-20221001/revision/49af0d4be8266217cb60bbc2bdb8e0ca0929b250 "HTTP/1.1 200 OK"

2026-02-28 08:45:38,936 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/lcw99/wikipedia-korean-20221001/resolve/49af0d4be8266217cb60bbc2bdb8e0ca0929b250/.huggingface.yaml "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/datasets/lcw99/wikipedia-korean-20221001/resolve/49af0d4be8266217cb60bbc2bdb8e0ca0929b250/.huggingface.yaml "HTTP/1.1 404 Not Found"

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-02-28 08:45:38,938 - WARNING - Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

2026-02-28 08:45:39,187 - INFO - HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lcw99/wikipedia-korean-20221001 "HTTP/1.1 200 OK"

HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lcw99/wikipedia-korean-20221001 "HTTP/1.1 200 OK"

2026-02-28 08:45:39,405 - INFO - HTTP Request: GET https://huggingface.co/api/datasets/lcw99/wikipedia-korean-20221001/tree/49af0d4be8266217cb60bbc2bdb8e0ca0929b250/data?recursive=true&expand=false "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/datasets/lcw99/wikipedia-korean-20221001/tree/49af0d4be8266217cb60bbc2bdb8e0ca0929b250/data?recursive=true&expand=false "HTTP/1.1 200 OK"

2026-02-28 08:45:39,601 - INFO - HTTP Request: GET https://huggingface.co/api/datasets/lcw99/wikipedia-korean-20221001/tree/49af0d4be8266217cb60bbc2bdb8e0ca0929b250?recursive=false&expand=false "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/datasets/lcw99/wikipedia-korean-20221001/tree/49af0d4be8266217cb60bbc2bdb8e0ca0929b250?recursive=false&expand=false "HTTP/1.1 200 OK"
Loaded rows: 300 (split=train[:300])

In [44]:
def clean_up_text(content: str) -> str:
    content = re.sub(r"(\w+)-\n(\w+)", r"\1\2", content)
    content = re.sub(r"\\n|  —|——————————|—————————|—————|\\u[\dA-Fa-f]{4}|\uf075|\uf0b7", "", content)
    content = re.sub(r"(\w)\s*-\s*(\w)", r"\1-\2", content)
    content = re.sub(r"\s+", " ", content)
    return content

documents = [
    Document(
        text=clean_up_text(row["text"]),
        doc_id=str(row["id"]),
        metadata={"title": str(row["title"])}
    )
    for _, row in data.iterrows()
]

In [45]:
data.head()

   id  \
0   5
1   9
2  10
3  19
4  20

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     제임스 얼 카터 주니어(, 1924년 10월 1일 ~ )는 민주당 출신 미국 39대 대통령 (1977년 ~ 1981년)이다.\n\n생애\n\n어린 시절 \n지미 카터는 조지아주 섬터 카운티 플레인스 마을에서 태어났다.\n\n조지아 공과대학교를 졸업하였다. 그 후 해군에 들어가 전함·원자력·잠수함의 승무원으로 일하였다. 1953년 미국 해군 대위로 예편하였고 이후 땅콩·면화 등을 가꿔 많은 돈을 벌었다. 그의 별명이 "땅콩 농부" (Peanut Farmer)로 알려졌다.\n\n정계 입문 \n1962년 조지아주 상원 의원 선거에서 낙선하나 그 선거가 부정선거 였음을 입증하게 되어 당선되고, 1966년 조지아 주지사 선거에 낙선하지만, 1970년 조지아 주지사를 역임했다. 대통령이 되기 전 조지아주 상원의원을 두번 연임했으며, 1971년부터 1975년까지 조지아 지사로 근무했다. 조지아 주지사로 지내면서, 미국에 사는 흑인 등용법을 내세웠다.\n\n대통령 재임 \n\n1976년 미합중국 제39대 대통령 선거에 민주당 후보로 출마하여 도덕주의 정책으로 내세워서, 많은 지지를 받고 제럴드 포드 대통령을 누르고 당선되었다.\n\n카터 대통령은 에너지 개발을 촉구했으나 공화당의 반대로 무산되었다.\n\n외교 정책 \n카터는 이집트와 이스라엘을 조정하여 캠프 데이비드에서 안와르 사다트 대통령과 메나헴 베긴 수상과 함께 중동 평화를 위한 캠프데이비드 협정을 체결했다. 이것은 공화당과 미국의 유대인 단체의 반발을 일으켰다. 그러나 1979년, 양국 간의 평화조약이 백악관에서 이루어졌다.\n\n소련과 제2차 전략 무기 제한 협상(SALT II)에 조인했다.\n\n카터는 1970년대 후반 당시 대한민국 등 인권 후진국의 국민들의 인권을 지키기 위해 노력했으며, 취임 이후 계속해서 도덕정치를 내세웠다.\n\n임기 말, 소련의 아프가니스탄 침공 사건으로 인해 1980년 하계 올림픽에 반공국가들의 보이콧을 하였다.\n\n그는 주이란 미국 대사관 인질 사건의 인질 구출 실패로 인한 원인으로, 1980년 제40대 대통령 선거에서 공화당의 로널드 레이건에게 패하며 재선에 실패하였다.\n\n대한민국과의 관계\n\n지미 카터는 대한민국과의 관계에서도 중요한 영향을 미쳤던 대통령 중 하나다. 인권 문제와 주한미군 철수 문제로 한때 한미 관계가 불편하기도 했다. [1978년 대한민국에 대한 북한의 위협에 대비해 한미연합사를 창설하면서, 1982년까지 3단계에 걸쳐 주한미군을 철수하기로 했다. 그러나 주한미군사령부와 정보기관·의회의 반대에 부딪혀 주한미군은 완전철수 대신 6,000명을 감축하는 데 그쳤다. 또한 박정희 정권의 인권 문제 등과의 논란으로 불협화음을 냈으나, 1979년 6월 하순, 대한민국을 방문하여 관계가 다소 회복되었다.\n1979년 ~ 1980년 대한민국의 정치적 격변기 당시의 대통령이었던 그는 이에 대해 애매한 태도를 보였고, 이는 후에 대한민국 내에서 고조되는 반미 운동의 한 원인이 됐다. 10월 26일, 박정희 대통령이 김재규 중앙정보부장에 의해 살해된 것에 대해 그는 이 사건으로 큰 충격을 받았으며, 사이러스 밴스 국무장관을 조문사절로 파견했다. 12·12 군사 반란과 5.17 쿠데타에 대해 초기에는 강하게 비난했으나, 미국 정부가 신군부를 설득하는데, 한계가 있었고 결국 묵인하는 듯한 태도를 보이게 됐다.\n\n퇴임 이후 \n\n퇴임 이후 민간 자원을 적극 활용한 비영리 기구인 카터 재단을 설립한 뒤 민주주의 실현을 위해 제 3세계의 선거 감시 활동 및 기니 벌레에 의한 드라쿤쿠르스 질병 방재를 위해 힘썼다. 미국의 빈곤층 지원 활동, 사랑의 집짓기 운동, 국제 분쟁 중재 등의 활동도 했다.\n\n카터는 카터 행정부 이후 미국이 북핵 위기, 코소보 전쟁, 이라크 전쟁과 같이 미국이 군사적 행동을 최후로 선택하는 전통적 사고를 버리고 군사적 행동을 선행하는 행위에 대해 깊은 유감을 표시 하며 미국의 군사적 활동에 강한 반대 입장을 보이고 있다.\n\n특히 국제 분쟁 조정을 위해 북한의 김일성, 아이티의 세드라스 장군, 팔레인스타인의 하마스, 보스니아의 세르비아계 정권 같이 미국 정부에 대해 협상을 거부하면서 사태의 위기를 초래한 인물 및 단체를 직접 만나 분쟁의 원인을 근본적으로 해결하기 위해 힘썼다. 이 과정에서 미국 행정부와 갈등을 보이기도 했지만, 전직 대통령의 권한과 재야 유명 인사들의 활약으로 해결해 나갔다.\n\n1978년에 채결된 캠프데이비드 협정의 이행이 지지부진 하자 중동 분쟁 분제를 해결하기 위해 1993년 퇴임 후 직접 이스라엘과 팔레인스타인의 오슬로 협정을 이끌어 내는 데도 성공했다.\n\n1993년 1차 북핵 위기 당시 북한에 대한 미국의 군사적 행동이 임박했으나, 미국 전직 대통령으로는 처음으로 북한을 방문하고 미국과 북 양국의 중재에 큰 기여를 해 위기를 해결했다는 평가를 받았다. 또한 이 때 김영삼 대통령과 김일성 주석의 만남을 주선했다. 하지만 그로부터 수주일 후 김일성이 갑자기 사망하여 김일성과 김영삼의 정상회담은 이루어지지 못했다.\n\n미국의 관타나모 수용소 문제, 세계의 인권문제에서도 관심이 깊어 유엔에 유엔인권고등판무관의 제도를 시행하도록 노력하여 독재자들의 인권 유린에 대해 제약을 하고, 국제형사재판소를 만드는 데 기여하여 독재자들 같은 인권유린범죄자를 재판소로 회부하여 국제적인 처벌을 받게 하는 등 인권 신장에 크나 큰 기여를 했다.\n2011년 4월 26일부터 29일까지 북한을 3일간 방문했다.\n\n평가 \n경제문제를 해결하지 못하고 주 이란 미국 대사관 인질 사건에 발목이 잡혀 실패한 대통령으로 평가를 받지만 이란 사태는 미국 내 이란 재산을 풀어주겠다는 조건을 내세워서 사실상 카터가 해결한 것이었고, 사랑의 집짓기 운동 등으로 퇴임 후에 훨씬 더 존경받는 미국 대통령 중에 특이한 인물로 남았다.\n\n그는 2002년 말 인권과 중재 역할에 대한 공로를 인정받아 노벨 평화상을 받게 되었다.\n\n이외에도, 그는 대통령 재임 시절은 물론 퇴임 후에도 지속적으로 여러 장기 집권중인 독재자들을 만나왔는데, 그와 만난 독재자들 중 절대 다수가 얼마 되지 않아 최후를 맞이하게 되며 '독재자의 사신'이라는 별명이 붙기도 했다.\n\n같이 보기 \n 주한 미군의 철수\n 한반도 평화협정\n\n역대 선거 결과\n\n각주\n\n참고 문헌 \n 《진정한 리더는 떠난 후에 아름답다》 저자 : 지미 카터\n 《지미 카터》 저자 : 지미 카터(지식의날개, 2018)\n\n외부 링크 \n \n \n\n \n1924년 출생\n1976년 미국 대통령 후보\n1980년 미국 대통령 후보\n그래미상 수상자\n노벨 평화상 수상자\n미국 해군의 장교\n미국의 침례교도\n미국의 노벨상 수상자\n미국의 농부\n미국의 대통령\n미국의 역사 (1964-1980)\n미국의 외교관\n미국의 인도주의자\n미국의 제2차 세계 대전 참전 군인\n미국의 진보주의\n민주당 (미국)의 정치인\n살아있는 사람\n스코틀랜드계 미국인\n아일랜드계 미국인\n잉글랜드계 미국인\n조지아 공과대학교 동문\n조지아주의 정치인\n조지아주지사\n미국의 회고록 작가\n에모리 대학교 교수\n미국 해군사관학교 동문\n미국 버지니아 종합군사학원 동문\n미국 미주리 종합군사학원 동문\n타임 올해의 인물\n군사 기술자\n이란 혁명 관련자\n미국의 민주주의 운동가\n주이란 미국 대사관 인질 사건\n조지아주의 민주당 당원\n조지아주 출신 작가\n소련-아프가니스탄 전쟁 관련자\n20세기 미국 사람\n21세기 미국 사람
1  수학(數學, , 줄여서 math)은 수, 양, 구조, 공간, 변화 등의 개념을 다루는 학문이다. 널리 받아들여지는 명확한 정의는 없으나 현대 수학은 일반적으로 엄밀한 논리에 근거하여 추상적 대상을 탐구하며, 이는 규칙의 발견과 문제의 제시 및 해결의 과정으로 이루어진다. 수학은 그 발전 과정에 있어서 철학, 과학과 깊은 연관을 맺고 있으며, 다만 엄밀한 논리와 특유의 추상성, 보편성에 의해 다른 학문들과 구별된다. 특히 수학은 과학의 여느 분야들과는 달리 자연계에서 관측되지 않는 개념들에 대해서까지 이론을 추상화시키는 특징을 보이는데, 수학자들은 그러한 개념들에 대한 추측을 제시하고 적절하게 선택된 정의와 공리로부터 엄밀한 연역을 거쳐 그 진위를 파악한다.\n\n수학의 개념들은 기원전 600년 경에 활동하며 최초의 수학자로도 여겨지는 탈레스의 기록은 물론, 다른 고대 문명들에서도 찾아볼 수 있으며 인류의 문명과 함께 발전해 왔다. 오늘날 수학은 자연과학, 사회과학, 공학, 의학 등 다른 여러 학문에서도 핵심적인 역할을 하며 다양한 방식으로 응용된다.\n\n수학을 의미하는 매스매틱스(mathematics)라는 단어는 '아는 모든 것', '배우는 모든 것'이라는 뜻의 고대 그리스어 'máthēma'(μάθημα) 및 그 활용형 mathēmatikós(μαθηματικός)에서 유래되었다.\n\n역사 \n\n역사적으로 고대부터 현대에 이르기까지 문명에 필수적인 건축, 천문학, 정치, 상업 등에 수학적 개념들이 응용되어 왔다. 교역·분배·과세 등 인류의 사회 생활에 필요한 모든 계산에 수학이 관여해 왔고, 농경 생활에 필수적인 천문 관측과 달력의 제정, 토지의 측량 또한 수학이 직접적으로 사용된 분야이다. 고대 수학을 크게 발전시킨 문명으로는 이집트, 인도, 중국, 그리스 등이 있다.\n\n특히 고대 그리스 문명에서는 처음으로 방정식에서 변수를 문자로 쓰는 등 추상화가 발전하였고 유클리드의 원론에서는 최초로 엄밀한 논증에 근거한 수학이 나타난다. 수학의 발전은 이후로도 계속되어 16세기의 르네상스에 이르러서는 과학적 방법과의 상호 작용을 통해 수학과 자연과학에 있어서 혁명적인 연구들이 진척되었고, 이는 인류 문명 발달에 큰 영향을 미치게 되었다.\n\n세부 분야 \n\n수학의 각 분야들은 상업에 필요한 계산을 하기 위해, 숫자들의 관계를 이해하기 위해, 토지를 측량하기 위해, 그리고 천문학적 사건들을 예견하기 위해 발전되어왔다. 이 네 가지 목적은 대략적으로 수학이 다루는 대상인 양, 구조, 공간 및 변화에 대응되며, 이들을 다루는 수학의 분야를 각각 산술, 대수학, 기하학, 해석학이라 한다. 또한 이 밖에도 근대 이후에 나타난 수학기초론과 이산수학 및 응용수학 등이 있다.\n\n산술 \n\n산술은 자연수와 정수 및 이에 대한 사칙연산에 대한 연구로서 시작했다. 수론은 이런 주제들을 보다 깊게 다루는 학문으로, 그 결과로는 페르마의 마지막 정리 등이 유명하다. 또한 쌍둥이 소수 추측과 골드바흐 추측 등을 비롯해 오랜 세월 동안 해결되지 않고 남아있는 문제들도 여럿 있다.\n\n수의 체계가 보다 발전하면서, 정수의 집합을 유리수의 집합의 부분집합으로 여기게 되었다. 또한 유리수의 집합은 실수의 집합의 부분집합이며, 이는 또다시 복소수 집합의 일부분으로 볼 수 있다. 여기에서 더 나아가면 사원수와 팔원수 등의 개념을 생각할 수도 있다. 이와는 약간 다른 방향으로, 자연수를 무한대까지 세어나간다는 개념을 형식화하여 순서수의 개념을 얻으며, 집합의 크기 비교를 이용하여 무한대를 다루기 위한 또다른 방법으로는 기수의 개념도 있다.\n\n대수학 \n\n수 대신 문자를 써서 문제해결을 쉽게 하는 것과, 마찬가지로 수학적 법칙을 일반적이고 간명하게 나타내는 것을 포함한다. 고전대수학은 대수방정식 및 연립방정식의 해법에서 시작하여 군, 환, 체 등의 추상대수학을 거쳐 현대에 와서는 대수계의 구조를 보는 것을 중심으로 하는 선형대수학으로 전개되었다. 수의 집합이나 함수와 같은 많은 수학적 대상들은 내재적인 구조를 보인다. 이러한 대상들의 구조적 특성들이 군론, 환론, 체론 그리고 그 외의 수많은 대수적 구조들을 연구하면서 다루어지며, 그것들 하나하나가 내재적 구조를 지닌 수학적 대상이다. 이 분야에서 중요한 개념은 벡터, 벡터 공간으로의 일반화, 그리고 선형대수학에서의 지식들이다. 벡터의 연구에는 산술, 대수, 기하라는 수학의 중요한 세개의 분야가 조합되어 있다. 벡터 미적분학은 여기에 해석학의 영역이 추가된다. 텐서 미적분학은 대칭성과 회전축의 영향 아래에서 벡터의 움직임을 연구한다. 눈금없는 자와 컴퍼스와 관련된 많은 고대의 미해결 문제들이 갈루아 이론을 사용하여 비로소 해결되었다.\n\n기하학 \n\n공간에 대한 연구는 기하학에서 시작되었고, 특히 유클리드 기하학에서 비롯되었다. 삼각법은 공간과 수들을 결합하였고, 잘 알려진 피타고라스의 정리를 포함한다. 현대에 와서 공간에 대한 연구는, 이러한 개념들은 더 높은 차원의 기하학을 다루기 위해 비유클리드 기하학(상대성이론에서 핵심적인 역할을 함)과 위상수학으로 일반화되었다. 수론과 공간에 대한 이해는 모두 해석 기하학, 미분기하학, 대수기하학에 중요한 역할을 한다. 리 군도 공간과 구조, 변화를 다루는데 사용된다. 위상수학은 20세기 수학의 다양한 지류속에서 괄목할만한 성장을 한 분야이며, 푸앵카레 추측과 인간에 의해서 증명되지 못하고 오직 컴퓨터로만 증명된 4색정리를 포함한다.\n\n해석학 \n\n변화에 대한 이해와 묘사는 자연과학에 있어서 일반적인 주제이며, 미적분학은 변화를 탐구하는 강력한 도구로서 발전되었다. 함수는 변화하는 양을 묘사함에 있어서 중추적인 개념으로써 떠오르게 된다. 실수와 실변수로 구성된 함수의 엄밀한 탐구가 실해석학이라는 분야로 알려지게 되었고, 복소수에 대한 이와 같은 탐구 분야는 복소해석학이라고 한다. 함수해석학은 함수의 공간(특히 무한차원)의 탐구에 주목한다. 함수해석학의 많은 응용분야 중 하나가 양자역학이다. 많은 문제들이 자연스럽게 양과 그 양의 변화율의 관계로 귀착되고, 이러한 문제들이 미분방정식으로 다루어진다. 자연의 많은 현상들이 동역학계로 기술될 수 있다. 혼돈 이론은 이러한 예측 불가능한 현상을 탐구하는 데 상당한 기여를 한다.\n\n수학기초론 관련 분야 \n\n수학의 기초를 확실히 세우기 위해, 수리논리학과 집합론이 발전하였고, 이와 더불어 범주론이 최근에도 발전되고 있다. “근본 위기”라는 말은 대략 1900년에서 1930년 사이에 일어난, 수학의 엄밀한 기초에 대한 탐구를 상징적으로 보여주는 말이다. 수학의 엄밀한 기초에 대한 몇 가지 의견 불일치는 오늘날에도 계속되고 있다. 수학의 기초에 대한 위기는 그 당시 수많은 논쟁에 의해 촉발되었으며, 그 논쟁에는 칸토어의 집합론과 브라우어-힐베르트 논쟁이 포함되었다.\n\n이산수학\n\n응용수학\n\n영향 \n오늘날 수학은 자연과학, 공학뿐만 아니라, 경제학 등의 사회과학에서도 중요한 도구로 사용된다. 예를 들어, 정도의 차이는 있으나, 미적분학과 선형대수학은 자연과학과 공학, 경제학을 하는데에 필수적 과목으로 여겨지며, 확률론은 계량경제학에 응용된다. 통계학은 사회과학 이론에 근거를 마련하는데 필수적이다. 16세기에 갈릴레오 갈릴레이가 "자연이라는 책은 수학이라는 언어로 기록되어 있다."는 주장과 함께 물리학에 수학적 방법을 도입하였고, 17세기에 아이작 뉴턴이 고전 역학의 기본 물리학 법칙들을 수학적으로 기술하고 정립하여 물리학 이론에서 수학적 모델링은 필수적 요소가 되었다. 또한 이 시기는 과학적 방법이 정립되는 시기이기도 한데, 많은 과학적 현상들이 수학적 관계가 있음이 드러나면서 과학적 방법에도 수학은 중요한 역할을 하고 있다. 노벨 물리학상 수상자 유진 위그너는 그의 에세이 "The unreasonable effectiveness of mathematics in natural sciences"에서 인간 세상과 동떨어져있고 현실과 아무 관련이 없다고 여겨지던 수학 중 극히 일부는 뜻밖에도 자연과학과 연관성이 드러나고 과학이론에 효과적인 토대를 마련해 주는데에 대한 놀라움을 표현하였다. 예를 들어, 비유클리드 기하학과 3차원 이상의 임의의 차원에서 기하학을 탐구했던 미분 기하학은 당시에는 현실과 연관성을 가지지 않았으나 먼 훗날 일반상대성이론이 4차원 기하학을 필요로 함에 따라, 물리적 세상과 연관이 있음이 밝혀졌다. 또한 게이지이론, 양자장론 등에도 미분 기하학은 필수적이다.\n\n또한 수학은 음악이나 미술 등 예술과도 관련이 있다. 피타고라스는 두 정수의 비율이 듣기 좋은 소리가 난다는 점을 가지고 피타고라스 음계를 만들었다. 중세시대에도 음악과 수학을 밀접하게 연관시켰으며 성 빅토르의 후고는 “음악은 조화다”라고 했고, 성 트론드의 루돌프는 “음악은 조화의 토대(ratio)다”라고 쓴 바 있다. 조화가 반드시 소리로 표현될 필요는 없고 소리의 음악은 음악의 형식 중 하나에 불과했다. 소리에 대해 다루었던 중세의 저술가들이 있는가 하면, 조화와 비례의 추상적 이론만을 다루고 소리에는 거의 관심을 보이지 않았던 저술가들도 있었다. 청각적인 면과 추상적인 면이라는 음악의 이런 이중적 측면은 고대의 음악이론보다는 중세의 음악이론에서 큰 특징이 되었다. 또한 현대 음악을 군(群,group)같은 수학적 대상을 이용해 분석하기도 한다. 원근법은 사영 기하학에 해당한다. 미술 사조 중 하나인 입체파도 기하학의 영향을 받았다.\n\n같이 보기 \n 정수론\n 기하학\n 대수학\n 해석학\n 산학\n 대한민국의 고등학교 수학 교과목\n 이산수학\n 응용수학\n 수학자\n\n참고 문헌 \n\n Eves, Howard, An Introduction to the History of Mathematics, Sixth Edition, Saunders, 1990, .\n Jourdain, Philip E. B., The Nature of Mathematics, in The World of Mathematics, James R. Newman, editor, Dover, 2003, .\n Peterson, Ivars, Mathematical Tourist, New and Updated Snapshots of Modern Mathematics, Owl Books, 2001, .</div>\n\n외부 링크 \n \n \n  대한수학회(KMS)\n  Mathworld\n  The MacTutor History of Mathematics archive\n\n \n형식과학\n수학 용어

In [46]:
pc = Pinecone(api_key=pinecone_api_key)

index_name = "vector"
target_dimension = 512
metric = "dotproduct"
spec = ServerlessSpec(cloud="aws", region="us-east-1")

existing = pc.list_indexes().names()

if index_name in existing:
    desc = pc.describe_index(index_name)
    current_dimension = desc["dimension"] if isinstance(desc, dict) else desc.dimension

    if current_dimension != target_dimension:
        raise ValueError(
            f"Existing index '{index_name}' dimension is {current_dimension}, "
            f"but target is {target_dimension}. "
            "Delete/recreate index or use a different index name."
        )
else:
    pc.create_index(
        name=index_name,
        dimension=target_dimension,
        metric=metric,
        spec=spec,
    )

while not pc.describe_index(index_name).status["ready"]:
    sleep(1)

pinecone_index = pc.Index(index_name)
vector_store = PineconeVectorStore(pinecone_index=pinecone_index)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

print(pinecone_index.describe_index_stats())

{'dimension': 512,
 'index_fullness': 0.0,
 'metric': 'cosine',
 'namespaces': {'': {'vector_count': 7140}},
 'total_vector_count': 7140,
 'vector_type': 'dense'}

In [47]:
# from llama_index.core import VectorStoreIndex
# from llama_index.core.node_parser import TokenTextSplitter
# from llama_index.core.schema import TextNode, MetadataMode

# # 병목 완화: 청크 수 감소 + 배치 확대 + 비동기
# CHUNK_SIZE = 1500
# CHUNK_OVERLAP = 150
# INSERT_BATCH_SIZE = 300
# RETRIEVAL_PROXY_CHARS = 2200

# splitter = TokenTextSplitter(chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP)
# nodes = splitter.get_nodes_from_documents(documents)

# safe_nodes = []
# for i, n in enumerate(nodes):
#     full_text = n.get_content(metadata_mode=MetadataMode.NONE)
#     proxy_text = full_text[:RETRIEVAL_PROXY_CHARS]

#     safe_nodes.append(
#         TextNode(
#             text=proxy_text,
#             id_=f"node-{i}",
#             metadata={"title": n.metadata.get("title", "")},
#         )
#     )

# print(f"chunks: {len(nodes)} -> indexed proxy chunks: {len(safe_nodes)}")

# vs_index = VectorStoreIndex(
#     nodes=safe_nodes,
#     storage_context=storage_context,
#     embed_model=embed_model,
#     insert_batch_size=INSERT_BATCH_SIZE,
#     use_async=True,
#     show_progress=True,
# )

In [48]:
stats = pinecone_index.describe_index_stats()
print(stats)

{'dimension': 512,
 'index_fullness': 0.0,
 'metric': 'cosine',
 'namespaces': {'': {'vector_count': 7140}},
 'total_vector_count': 7140,
 'vector_type': 'dense'}

In [49]:
sample_ids = []
for ids in pinecone_index.list(namespace=""):
    sample_ids.extend(ids)
    if len(sample_ids) >= 5:
        break

sample_ids = sample_ids[:5]
print("sample_ids:", sample_ids)

fetched = pinecone_index.fetch(ids=sample_ids, namespace="")
print(fetched)

sample_ids: ['node-0', 'node-1', 'node-10', 'node-100', 'node-1000']

In [50]:
qvec = embed_model.get_text_embedding("테스트 질의")
res = pinecone_index.query(
    vector=qvec,
    top_k=5,
    include_values=False,
    include_metadata=True,
    namespace="",
)
print(res)

2026-02-28 08:45:45,739 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
{'matches': [{'id': 'node-1797',
              'metadata': {'_node_content': '{"id_": "node-1797", "embedding": '
                                            'null, "metadata": {}, '
                                            '"excluded_embed_metadata_keys": '
                                            '[], "excluded_llm_metadata_keys": '
                                            '[], "relationships": {}, '
                                            '"metadata_template": "{key}: '
                                            '{value}", "metadata_separator": '
                                            '"\\n", "text": "랩톤 그리고 끈이론. 2015년 '
                                            '6월 10일. 기본 입자 페르미 입자 양자색역학 피네간의 '
                                            '경야", "mimetype": "text/plain", '
                                            '"start_char_idx": null, '
                                            '"end_char_idx": null, '
                                            '"text_template": '
                                            '"{metadata_str}\\n\\n{content}", '
                                            '"class_name": "TextNode"}',
                           '_node_type': 'TextNode',
                           'doc_id': 'None',
                           'document_id': 'None',
                           'ref_doc_id': 'None'},
              'score': 0.423211098,
              'values': []},
             {'id': 'node-3584',
              'metadata': {'_node_content': '{"id_": "node-3584", "embedding": '
                                            'null, "metadata": {}, '
                                            '"excluded_embed_metadata_keys": '
                                            '[], "excluded_llm_metadata_keys": '
                                            '[], "relationships": {}, '
                                            '"metadata_template": "{key}: '
                                            '{value}", "metadata_separator": '
                                            '"\\n", "text": "L형과 D형의 비율 자체에 '
                                            '대해서 묻는 것은 밀러실험과 무관하며, 효소와의 반응에 대한 '
                                            '것은 단백질학에서 연구하고 있는 중이다. D형 아미노산도 '
                                            '실제로 사용(박테리아의 세포벽과 미토콘드리아의 일부 '
                                            '단백질)이 되며, 리보자임이 존재함으로 인해 효소 자체가 '
                                            '문제가 있다는 주장 역시 성립하지 않는다. 다른 실험들 '
                                            '폭스의 실험으로 아미노산", "mimetype": '
                                            '"text/plain", "start_char_idx": '
                                            'null, "end_char_idx": null, '
                                            '"text_template": '
                                            '"{metadata_str}\\n\\n{content}", '
                                            '"class_name": "TextNode"}',
                           '_node_type': 'TextNode',
                           'doc_id': 'None',
                           'document_id': 'None',
                           'ref_doc_id': 'None'},
              'score': 0.398436069,
              'values': []},
             {'id': 'node-5422',
              'metadata': {'_node_content': '{"id_": "node-5422", "embedding": '
                                            'null, "metadata": {}, '
                                            '"excluded_embed_metadata_keys": '
                                            '[], "excluded_llm_metadata_keys": '
                                            '[], "relationships": {}, '
                                            '"metadata_template": "{key}: '
                                            '{value}", "metadata_separator": '
                                            '"\\n", "text": "주의해야 한다. 또 헬륨은 '
                                            '트리믹스에 사용되는데, 트리믹스는 압축 공기에서 질소의 '
                                            '비율을 줄이고 그만큼을 헬륨으로 채운 것이다. 헬륨은 '
                                            '용해도가 매우 낮기 때문에 압축 공기를 사용했을 '
                                            '때(30~40m)보다 더욱 깊이 잠수할 수 있다. 그러나 '
                                            '70m~80m 정도까지 내려가면 헬륨이 용해되어 헬륨 마취 '
                                            '현상이 일어난다. 핵융합", "mimetype": '
                                            '"text/plain", "start_char_idx": '
                                            'null, "end_char_idx": null, '
                                            '"text_template": '
                                            '"{metadata_str}\\n\\n{content}", '
                                            '"class_name": "TextNode"}',
                           '_node_type': 'TextNode',
                           'doc_id': 'None',
                           'document_id': 'None',
                           'ref_doc_id': 'None'},
              'score': 0.383832455,
              'values': []},
             {'id': 'node-5122',
              'metadata': {'_node_content': '{"id_": "node-5122", "embedding": '
                                            'null, "metadata": {}, '
                                            '"excluded_embed_metadata_keys": '
                                            '[], "excluded_llm_metadata_keys": '
                                            '[], "relationships": {}, '
                                            '"metadata_template": "{key}: '
                                            '{value}", "metadata_separator": '
                                            '"\\n", "text": "빈혈증에 걸린 환자 각각은 '
                                            '적혈구에서 변형된 형태의 헤모글로빈을 가지고 있음을 '
                                            '증명했다. 그리고 겸형 적혈구 형질을 가진 사람들은 정상과 '
                                            '비정상 형태의 헤모글로빈 모두를 가지고 있음이 확인되었다. '
                                            '이는 멘델 유전이 단순히 단백질의 존재를 결정하는 것이 '
                                            '아니라 단백질의 특정한 물리적 특성까지 결정함을", '
                                            '"mimetype": "text/plain", '
                                            '"start_char_idx": null, '
                                            '"end_char_idx": null, '
                                            '"text_template": '
                                            '"{metadata_str}\\n\\n{content}", '
                                            '"class_name": "TextNode"}',
                           '_node_type': 'TextNode',
                           'doc_id': 'None',
                           'document_id': 'None',
                           'ref_doc_id': 'None'},
              'score': 0.382971287,
              'values': []},
             {'id': 'node-5313',
              'metadata': {'_node_content': '{"id_": "node-5313", "embedding": '
                                            'null, "metadata": {}, '
                                            '"excluded_embed_metadata_keys": '
                                            '[], "excluded_llm_metadata_keys": '
                                            '[], "relationships": {}, '
                                            '"metadata_template": "{key}: '
                                            '{value}", "metadata_separator": '
                                            '"\\n", "text": "측정하여 작동한다. 같이 보기 '
                                            'LG 프라다 아이폰 아이팟 터치 멀티터치 각주", '
                                            '"mimetype": "text/plain", '
                                            '"start_char_idx": null, '
                                            '"end_char_idx": null, '
                                            '"text_template": '
                                            '"{metadata_str}\\n\\n{content}", '
                                            '"class_name": "TextNode"}',
                           '_node_type': 'TextNode',
                           'doc_id': 'None',
                           'document_id': 'None',
                           'ref_doc_id': 'None'},
              'score': 0.382763326,
              'values': []}],
 'namespace': '',
 'usage': {'read_units': 1}}

In [51]:
index = VectorStoreIndex.from_vector_store(
    vector_store=vector_store,
    embed_model=embed_model,
)
index_stats = pinecone_index.describe_index_stats()
index_stats

{'dimension': 512,
 'index_fullness': 0.0,
 'metric': 'cosine',
 'namespaces': {'': {'vector_count': 7140}},
 'total_vector_count': 7140,
 'vector_type': 'dense'}

In [52]:
from llama_index.core import VectorStoreIndex
from llama_index.core.tools import QueryEngineTool, ToolMetadata
from llama_index.core.agent import AgentWorkflow
from llama_index.llms.openai import OpenAI

# pc = Pinecone(api_key=...)
# # pc_index = pc.Index(index_name)  # 기존 인덱스
# vector_store = PineconeVectorStore(pinecone_index=pc_index)

index = VectorStoreIndex.from_vector_store(vector_store=vector_store)

OPENAI_MODEL = "gpt-4o-mini"

agents = {}
for title in data["title"].dropna().unique():
    vector_query_engine = index.as_query_engine(
        vector_store_kwargs={"filter": {"title": title}}
    )

    query_engine_tools = [
        QueryEngineTool(
            query_engine=vector_query_engine,
            metadata=ToolMetadata(
                name="vector_tool",
                description=f"{title}에 대해서 물어볼 때 사용"
            ),
        ),
    ]

    function_llm = OpenAI(model=OPENAI_MODEL, temperature=0)
    agent = AgentWorkflow.from_tools_or_functions(
        tools_or_functions=query_engine_tools,
        llm=function_llm,
        verbose=True,
    )

    agents[title] = agent

In [53]:
handler = agents["지미 카터"].run(user_msg="이 인물 핵심 요약")
result = await handler
print(result.response.content)

2026-02-28 08:45:47,651 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-02-28 08:45:48,041 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

2026-02-28 08:45:53,985 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

2026-02-28 08:45:54,466 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

CancelledError:

In [ ]:
#생성된 에이전트 확인
agents

{'지미 카터': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13920e870>,
 '수학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x1398d95e0>,
 '수학 상수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3e7440>,
 '문학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3e6f90>,
 '나라 목록': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3e52e0>,
 '화학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3e7c20>,
 '체첸 공화국': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3e6fc0>,
 '맥스웰 방정식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3e6510>,
 '초월수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3e5b80>,
 '음계': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e587d0>,
 '대한민국 제16대 대통령 선거': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e58320>,
 '함석헌': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e59a30>,
 '백남준': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e588c0>,
 '2002년': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e5a9f0>,
 '12월 19일': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e5b560>,
 '5월 31일': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e584a0>,
 '6월 30일': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e59be0>,
 '우크라이나': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e58590>,
 '가위': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x139e5acc0>,
 '위키': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x1397bd160>,
 '지구과학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x1397bfd40>,
 '아오조라 문고': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a2085f0>,
 '프로젝트 구텐베르크': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a2082f0>,
 '겐지모노가타리': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a208590>,
 '귄터 그라스': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a208d40>,
 '일반 상대성이론': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a209040>,
 '데니스 리치': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a2093a0>,
 '주기율표': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a209700>,
 '아미노산': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a209a60>,
 '히라가나': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a209dc0>,
 '나라 이름순 수도 목록': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20a120>,
 '토마스 만': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20a480>,
 '하인리히 뵐': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20a7e0>,
 '방정식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20ab40>,
 '삼각함수 항등식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20aea0>,
 '노무현': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20b200>,
 '곱셈적 함수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20b560>,
 '체비쇼프 다항식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20b8c0>,
 '파이의 날': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20bc20>,
 '코사인 법칙': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a20bf80>,
 '사인 법칙': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3a8320>,
 '벡터 공간': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3a8680>,
 '펜로즈 삼각형': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3a89e0>,
 '수론적 함수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3a8d40>,
 '물리 상수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3a90a0>,
 '대수학의 기본 정리': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3a9400>,
 '정규 분포': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3a9760>,
 '공각기동대': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3a9ac0>,
 '뫼비우스 반전 공식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3a9e20>,
 '푸리에 급수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3aa180>,
 '가수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3aa4e0>,
 '감마 함수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3aa840>,
 '아쿠타가와 류노스케': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3aaba0>,
 '장국영': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3aaf00>,
 '통계학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3ab260>,
 '컴퓨터 과학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3ab5c0>,
 '위키백과': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3ab920>,
 '그리스 신들의 가계도': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3abc80>,
 '광자': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3abfe0>,
 '보손': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a318380>,
 '디리클레 합성곱': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3186e0>,
 '동치관계': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a318a40>,
 '자연철학의 수학적 원리': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a318da0>,
 '슈뢰딩거 방정식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a319100>,
 '엔트로피': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a319460>,
 '라플라스 방정식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3197c0>,
 '적분표': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a319b20>,
 '삼각함수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a319e80>,
 '르장드르 다항식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a31a1e0>,
 '소수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a31a540>,
 '로봇': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a31a8a0>,
 '깊은 생각': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a31ac00>,
 '표준 모형': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a31af60>,
 '쿼크': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a31b2c0>,
 '중력 상수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a31b620>,
 '변형력': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a31b980>,
 '대수학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a31bce0>,
 '군론': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a348080>,
 '선형 결합': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3483e0>,
 '파동 방정식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a348740>,
 '비오-사바르 법칙': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a348aa0>,
 '구골': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a348e00>,
 '구글': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a349160>,
 '코리올리 효과': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3494c0>,
 '벡터곱': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a349820>,
 '빅토르 초이': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a349b80>,
 '무리수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a349ee0>,
 '플랑크 상수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a34a240>,
 '막스 플랑크': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a34a5a0>,
 '포인팅 벡터': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a34a900>,
 '미세 구조 상수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a34ac60>,
 '크라메르 법칙': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a34afc0>,
 '행렬식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a34b320>,
 '리만 제타 함수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a34b680>,
 '좌표계': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a34b9e0>,
 '힐베르트 공간': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a34bd40>,
 '양자역학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3780e0>,
 '양자역학의 수학 공식화': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a378440>,
 '베르너 하이젠베르크': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3787a0>,
 '중국의 역사': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a378b00>,
 '브라-켓 표기법': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a378e60>,
 '대한민국': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a3791c0>,
 '대한민국의 국가': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a379520>,
 '노벨 물리학상': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a379880>,
 '안익태': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a379be0>,
 '서울특별시': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a379f40>,
 '앙카라': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a37a2a0>,
 '가속도': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a37a600>,
 '속도': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a37a960>,
 '운동량': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a37acc0>,
 '도모나가 신이치로': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a37b020>,
 '유카와 히데키': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a37b380>,
 '정몽헌': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a37b6e0>,
 '한국': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a37ba40>,
 '미분방정식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a37bda0>,
 '각운동량': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a088140>,
 '원주율': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0884a0>,
 '일리야 프리고진': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a088800>,
 '엔탈피': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a088b60>,
 '운동 에너지': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a088ec0>,
 '가타카나': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a089220>,
 '다양체': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a089580>,
 '정주영': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0898e0>,
 '마틴 가드너': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a089c40>,
 '프리먼 다이슨': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a089fa0>,
 '만프레트 아이겐': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a08a300>,
 '린 마굴리스': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a08a660>,
 '사람': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a08a9c0>,
 '아널드 슈워제네거': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a08ad20>,
 'GNU 자유 문서 사용 허가서': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a08b080>,
 'GNU': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a08b3e0>,
 '셀빅': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a08b740>,
 '밀러와 유리의 실험': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a08baa0>,
 '물': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a08be00>,
 '외계어 (통신언어)': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0301a0>,
 '콜라츠 추측': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a030500>,
 '전자 게시판': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a030860>,
 '정보': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a030bc0>,
 '위키낱말사전': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a030f20>,
 '채팅': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a031280>,
 '캠': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0315e0>,
 'PC통신': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a031940>,
 '통신체': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a031ca0>,
 '네트워크': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a032000>,
 '햄버거': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a032360>,
 '놀이': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0326c0>,
 '비디오 게임': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a032a20>,
 '리처드 도킨스': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a032d80>,
 '막스 델브뤼크': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0330e0>,
 '유리수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a033440>,
 '피시방': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0337a0>,
 '노동조합': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a033b00>,
 '자연로그의 밑': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a033e60>,
 '방일영': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05c200>,
 '자유 소프트웨어 재단': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05c560>,
 '자유 소프트웨어': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05c8c0>,
 'GNU 일반 공중 사용 허가서': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05cc20>,
 '일본어': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05cf80>,
 '허수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05d2e0>,
 '선형대수학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05d640>,
 '커널 (컴퓨팅)': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05d9a0>,
 '도스': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05dd00>,
 '라플라스 변환': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05e060>,
 'IBM': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05e3c0>,
 '프랙탈': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05e720>,
 '초파리과': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05ea80>,
 '2003년': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05ede0>,
 '1913년': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05f140>,
 '2001년': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05f4a0>,
 '1950년대': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05f800>,
 '20세기': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05fb60>,
 '실수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a05fec0>,
 '한국대학총학생회연합': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c0260>,
 '조선일보': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c05c0>,
 '스칼라 (수학)': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c0920>,
 '자연수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c0c80>,
 '스타크래프트': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c0fe0>,
 '그레고리 하인스': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c1340>,
 '시삽': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c16a0>,
 '8월 15일': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c1a00>,
 '8월 16일': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c1d60>,
 '칸토어 집합': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c20c0>,
 '구간': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c2420>,
 '부등식': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c2780>,
 '8월 13일': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c2ae0>,
 '마거릿 미첼': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c2e40>,
 '5월': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c31a0>,
 '음수': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c3500>,
 '이디 아민': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c3860>,
 '일본 문학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c3bc0>,
 '거리 공간': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0c3f20>,
 '위상 공간': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f02c0>,
 '위상 공간 (수학)': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f0620>,
 'P2P': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f0980>,
 '메신저': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f0ce0>,
 '선택 공리': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f1040>,
 '불교': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f13a0>,
 '안토니오 살리에리': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f1700>,
 '공학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f1a60>,
 '라이너스 폴링': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f1dc0>,
 '빌 클린턴': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f2120>,
 '레온하르트 오일러': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f2480>,
 '중국어 방': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f27e0>,
 '컴퓨터 파일': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f2b40>,
 '개인 정보 단말기': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f2ea0>,
 '개인용 컴퓨터': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f3200>,
 '터치스크린': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f3560>,
 '백과사전': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f38c0>,
 '자연과학': <llama_index.core.agent.workflow.multi_agent_workflow.AgentWorkflow at 0x13a0f3c20>,

In [ ]:
nodes = []
for title in data["title"].dropna().unique():
    doc_summary = (
        f"이것은 {title}과 관련된 내용이 있습니다. "
        f"{title}과 관련된 내용을 확인하는 용도로 이 인덱스를 사용하세요."
    )
    node = IndexNode(text=doc_summary, index_id=title)
    nodes.append(node)

In [ ]:
title_query_engines = {}
for title in data["title"].dropna().unique():
    title_query_engines[title] = index.as_query_engine(
        vector_store_kwargs={"filter": {"title": title}}
    )

vector_index = VectorStoreIndex(nodes, embed_model=embed_model)
vector_retriever = vector_index.as_retriever(similarity_top_k=1)

recursive_retriever = RecursiveRetriever(
    "vector",
    retriever_dict={"vector": vector_retriever},
    query_engine_dict=title_query_engines,
    verbose=True,
)

response_synthesizer = get_response_synthesizer(response_mode="compact")

query_engine = RetrieverQueryEngine.from_args(
    recursive_retriever,
    response_synthesizer=response_synthesizer,
)

2026-02-26 17:25:45,970 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

2026-02-26 17:25:46,188 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

2026-02-26 17:25:46,462 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

In [ ]:
# 해당 문서에서만 답변 가능한 굉장히 구체적인 질문 테스트
response = query_engine.query("셀빅에 대해 알려줘")

2026-02-26 17:25:46,648 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

Retrieving with query id None: 셀빅에 대해 알려줘
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
Retrieved node with id, entering: 셀빅
Retrieving with query id 셀빅: 셀빅에 대해 알려줘

2026-02-26 17:25:49,402 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Got response: 셀빅은 대한민국에서 생산된 PDA의 일종으로, jTel에서 개발하였으며 후에 코오롱에 인수되어 Cellvic으로 이름이 변경되었습니다. 이 제품은 팜 파일럿을 벤치마크하여 한국 환경에 맞춘 자체 운영 체제를 갖추고 있으며, 한국 최초의 PDA OS로 중요한 의미를 지닙니다. jTel은 애플리케이션 공모전을 통해 다양한 애플리케이션을 확보하고, 개인 개발자들을 지원하여 많은 애플리케이션이 개발되었습니다. 셀빅은 한글 지원이 원활하며, 다양한 모델이 출시되었으나, 2004년부터 후속 지원이 중단되었습니다.

2026-02-26 17:25:51,910 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

In [ ]:
response

Response(response='셀빅은 대한민국에서 개발된 PDA로, jTel에서 시작하여 코오롱에 인수된 후 Cellvic으로 이름이 변경되었습니다. 이 제품은 한국 환경에 맞춘 자체 운영 체제를 갖추고 있으며, 한국 최초의 PDA OS로 중요한 의미를 지닙니다. jTel은 애플리케이션 공모전을 통해 다양한 애플리케이션을 확보하고 개인 개발자들을 지원하여 많은 애플리케이션이 개발되었습니다. 셀빅은 한글 지원이 원활하며, 여러 모델이 출시되었으나 2004년부터 후속 지원이 중단되었습니다.', source_nodes=[NodeWithScore(node=TextNode(id_='358d51f6-443e-411b-91f1-d2700e08389c', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text='Query: 셀빅에 대해 알려줘\nResponse: 셀빅은 대한민국에서 생산된 PDA의 일종으로, jTel에서 개발하였으며 후에 코오롱에 인수되어 Cellvic으로 이름이 변경되었습니다. 이 제품은 팜 파일럿을 벤치마크하여 한국 환경에 맞춘 자체 운영 체제를 갖추고 있으며, 한국 최초의 PDA OS로 중요한 의미를 지닙니다. jTel은 애플리케이션 공모전을 통해 다양한 애플리케이션을 확보하고, 개인 개발자들을 지원하여 많은 애플리케이션이 개발되었습니다. 셀빅은 한글 지원이 원활하며, 다양한 모델이 출시되었으나, 2004년부터 후속 지원이 중단되었습니다.', mimetype='text/plain', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}'), score=0.5142472164885874)], metadata={'358d51f6-443e-411b-91f1-d2700e08389c': {}})

In [ ]:
response.response

'셀빅은 대한민국에서 개발된 PDA로, jTel에서 시작하여 코오롱에 인수된 후 Cellvic으로 이름이 변경되었습니다. 이 제품은 한국 환경에 맞춘 자체 운영 체제를 갖추고 있으며, 한국 최초의 PDA OS로 중요한 의미를 지닙니다. jTel은 애플리케이션 공모전을 통해 다양한 애플리케이션을 확보하고 개인 개발자들을 지원하여 많은 애플리케이션이 개발되었습니다. 셀빅은 한글 지원이 원활하며, 여러 모델이 출시되었으나 2004년부터 후속 지원이 중단되었습니다.'

In [ ]:
# Response 객체 내부 key
print(response.__dict__.keys())

# metadata 딕셔너리 key
print(response.metadata.keys())

# source_nodes 각 노드 metadata key
for i, n in enumerate(response.source_nodes):
    print(i, n.node.metadata.keys())

dict_keys(['response', 'source_nodes', 'metadata'])
dict_keys(['358d51f6-443e-411b-91f1-d2700e08389c'])
0 dict_keys([])

In [ ]:
response = query_engine.query("한국 강의 종류에 대해서 알려줘")

2026-02-26 17:25:52,093 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

Retrieving with query id None: 한국 강의 종류에 대해서 알려줘
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
Retrieved node with id, entering: 한국
Retrieving with query id 한국: 한국 강의 종류에 대해서 알려줘

2026-02-26 17:25:54,173 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Got response: 한국의 강은 다양한 종류가 있으며, 주요 강으로는 한강, 낙동강, 금강, 영산강 등이 있습니다. 이들 강은 각각의 지역에서 중요한 역할을 하며, 수자원 공급, 농업, 교통 등 다양한 용도로 사용됩니다. 한강은 서울을 가로지르며, 낙동강은 경상도를 흐르고, 금강은 충청도를 지나며, 영산강은 전라도를 흐릅니다. 각 강은 그 지역의 생태계와 문화에도 큰 영향을 미치고 있습니다.

2026-02-26 17:25:56,857 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

In [ ]:
response.response

'한국의 강은 여러 종류가 있으며, 주요 강으로는 한강, 낙동강, 금강, 영산강 등이 있습니다. 이들 강은 각 지역에서 중요한 역할을 하며, 수자원 공급, 농업, 교통 등 다양한 용도로 사용됩니다. 한강은 서울을 가로지르고, 낙동강은 경상도를 흐르며, 금강은 충청도를 지나고, 영산강은 전라도를 흐릅니다. 각 강은 그 지역의 생태계와 문화에도 큰 영향을 미치고 있습니다.'

## 실전 운영 전략: 테이블별 에이전트 난립을 피하는 리팩터링

현재 실습은 테이블마다 전용 엔진(에이전트)을 만들어 라우팅하는 개념 검증(POC)으로 매우 좋다.
다만 운영 환경에서 테이블 수가 커질수록(수천~수만) `엔진 객체 수`, `초기화 시간`, `라우팅 오탐`이 빠르게 비용으로 전환된다.

아래 리팩터링은 다음 원칙을 따른다.

1. **Lazy Initialization**
   - 모든 테이블 엔진을 미리 만들지 않고, 실제로 선택된 테이블만 생성/캐시한다.
2. **Top-k Routing**
   - `top_k=1` 고정 대신, 상위 후보 테이블 몇 개를 고른 뒤 최종 답변을 합성한다.
3. **계층형 후보 축소 (Domain -> Table)**
   - 제목/메타데이터를 이용해 도메인 후보를 먼저 좁히고, 그 안에서 테이블 라우팅을 수행한다.
4. **운영 가시성**
   - 어떤 도메인/테이블이 선택됐는지 로그를 남겨 실패 원인을 추적할 수 있게 한다.

> 핵심: **"테이블당 에이전트 고정 생성"에서 "필요할 때만 생성 + 후보 축소" 구조로 전환**

In [ ]:
from typing import Dict, List, Optional
from llama_index.core import Settings, VectorStoreIndex
from llama_index.core.schema import IndexNode

# 사전 조건: 기존 셀에서 data(컬럼: title), index(VectorStoreIndex)가 생성되어 있어야 함
required_vars = ["data", "index"]
missing = [name for name in required_vars if name not in globals()]
if missing:
    raise ValueError(f"Missing required variables: {missing}. Run previous cells first.")


class ProductionTableRouter:
    """
    운영형 라우터
    - domain_router: 도메인 후보를 먼저 축소
    - table_router: 선택된 도메인 내에서 테이블 top-k 선택
    - lazy cache: 선택된 테이블 query engine만 생성
    """

    def __init__(
        self,
        base_index: VectorStoreIndex,
        table_titles: List[str],
        domain_rules: Optional[Dict[str, List[str]]] = None,
    ):
        self.base_index = base_index
        self.table_titles = table_titles
        self._engine_cache: Dict[str, object] = {}

        # 규칙 기반 도메인 매핑 (프로덕션에서는 별도 카탈로그/메타스토어 권장)
        self.domain_rules = domain_rules or {
            "finance": ["revenue", "profit", "asset", "stock", "market", "billionaire"],
            "people": ["person", "name", "age", "rank", "ceo", "founder"],
            "geography": ["country", "city", "region", "nation"],
            "other": [],
        }

        self.title_to_domain = {title: self._infer_domain(title) for title in self.table_titles}

        # 1) 도메인 라우터 인덱스
        domain_nodes = []
        for domain, keywords in self.domain_rules.items():
            text = f"domain={domain}; keywords={', '.join(keywords)}"
            domain_nodes.append(IndexNode(text=text, index_id=f"domain::{domain}"))
        self.domain_index = VectorStoreIndex(domain_nodes)

        # 2) 테이블 라우터 인덱스 (짧은 proxy 텍스트만 사용)
        table_nodes = []
        for title in self.table_titles:
            domain = self.title_to_domain[title]
            summary = f"table={title}; domain={domain}; use when query is about {title}"
            table_nodes.append(IndexNode(text=summary, index_id=title))
        self.table_index = VectorStoreIndex(table_nodes)

    def _infer_domain(self, title: str) -> str:
        t = str(title).lower()
        for domain, keywords in self.domain_rules.items():
            if any(k in t for k in keywords):
                return domain
        return "other"

    def _get_engine(self, title: str):
        # lazy init + cache
        if title not in self._engine_cache:
            self._engine_cache[title] = self.base_index.as_query_engine(
                vector_store_kwargs={"filter": {"title": title}}
            )
        return self._engine_cache[title]

    @staticmethod
    def _extract_index_id(node_with_score) -> Optional[str]:
        node = getattr(node_with_score, "node", node_with_score)
        return getattr(node, "index_id", None)

    def _route_domains(self, question: str, top_k_domains: int = 2) -> List[str]:
        retriever = self.domain_index.as_retriever(similarity_top_k=top_k_domains)
        hits = retriever.retrieve(question)
        domains = []
        for h in hits:
            idx = self._extract_index_id(h)
            if idx and idx.startswith("domain::"):
                domains.append(idx.split("::", 1)[1])
        return domains or ["other"]

    def _route_tables(self, question: str, allowed_domains: List[str], top_k_tables: int = 4) -> List[str]:
        # 2단계 라우팅: 전체 라우터 결과를 받은 뒤 도메인으로 필터
        retriever = self.table_index.as_retriever(similarity_top_k=max(top_k_tables * 3, top_k_tables))
        hits = retriever.retrieve(question)

        selected = []
        for h in hits:
            title = self._extract_index_id(h)
            if not title:
                continue
            if self.title_to_domain.get(title, "other") in allowed_domains and title not in selected:
                selected.append(title)
            if len(selected) >= top_k_tables:
                break

        # 도메인 필터 후 비어 있으면 fallback
        if not selected:
            for h in hits:
                title = self._extract_index_id(h)
                if title and title not in selected:
                    selected.append(title)
                if len(selected) >= top_k_tables:
                    break

        return selected

    def query(self, question: str, top_k_domains: int = 2, top_k_tables: int = 3, debug: bool = True):
        routed_domains = self._route_domains(question, top_k_domains=top_k_domains)
        routed_tables = self._route_tables(question, routed_domains, top_k_tables=top_k_tables)

        partial_answers = []
        for title in routed_tables:
            qe = self._get_engine(title)
            try:
                ans = qe.query(question)
                partial_answers.append((title, str(ans)))
            except Exception as e:
                partial_answers.append((title, f"[ERROR] {e}"))

        context = "\n\n".join([f"[table={t}]\n{a}" for t, a in partial_answers])
        final_prompt = (
            "You are a synthesis assistant.\n"
            "Combine the partial answers into one final answer.\n"
            "If conflicts exist, mention them explicitly.\n\n"
            f"Question: {question}\n\n"
            f"Partial Answers:\n{context}"
        )

        final = Settings.llm.complete(final_prompt)
        final_text = getattr(final, "text", str(final))

        if debug:
            print("routed_domains:", routed_domains)
            print("routed_tables:", routed_tables)
            print("cached_engines:", len(self._engine_cache))

        return {
            "answer": final_text,
            "routed_domains": routed_domains,
            "routed_tables": routed_tables,
            "partial_answers": partial_answers,
        }


# ===== Usage =====
titles = [t for t in data["title"].dropna().unique().tolist()]
router = ProductionTableRouter(base_index=index, table_titles=titles)

result = router.query(
    "Who is the richest person and what country are they from?",
    top_k_domains=2,
    top_k_tables=3,
    debug=True,
)

print(result["answer"])

## 현재 노트북 전략 평가 (강점/한계/개선점)

### 강점
- **검색 청크와 답변 청크 분리**라는 핵심 아이디어를 정확히 구현함
- PDF 본문 파싱 한계를 테이블 추출(`camelot`) + 전용 질의엔진으로 보완함
- `RecursiveRetriever` 기반 라우팅으로 검색 범위를 줄여 비용 절감 가능성을 보임

### 한계
- 테이블 수가 증가하면 `테이블별 엔진` 객체 관리 비용이 급증
- 라우팅 프록시가 단순 요약문 위주라 오탐/누락 가능
- `top_k=1` 중심 전략은 누락 리스크가 큼
- 운영 관점 메타데이터(품질, 최신성, 소유자, 보안등급, 시간범위) 미반영

### 개선점
1. **Ingestion 표준화**: 원본별 파싱 품질지표를 남기고 정규화된 테이블 카탈로그 생성
2. **Metadata-first 라우팅**: 도메인/기간/엔티티로 후보를 선필터링 후 벡터 검색
3. **Lazy Engine + Cache**: 선택된 테이블만 엔진 생성
4. **Top-k + 재합성**: 후보 테이블 여러 개를 조회 후 최종 합성
5. **관측성(Observability)**: 라우팅 경로, 지연, 실패율, 비용 로그 축적

## 실무 전략: 전처리 -> 테이블 적재 -> 쿼리 라우팅

### 1) 전처리/적재 케이스 분류
- **Case A. Native Table PDF/HTML/CSV**: 구조 파싱 후 컬럼 표준화
- **Case B. Scan/OCR 문서**: OCR -> 레이아웃 복원 -> 신뢰도(score) 저장
- **Case C. 반정형 문서(보고서/공지)**: 섹션/키밸류 추출 후 사실 테이블화
- **Case D. 이벤트 로그/트랜잭션**: 시계열 파티션, 중복제거, 스키마 버저닝

### 2) 테이블 모델링 원칙
- `raw -> curated -> serving` 3계층으로 분리
- serving 계층은 **질의 단위**로 설계 (예: `billionaire_profile`, `billionaire_yearly_rank`)
- 모든 테이블에 최소 메타데이터 부착: 
  - `table_id, domain, entities, time_grain, updated_at, quality_score, pii_level`

### 3) 라우팅 전략
1. 쿼리에서 의도/엔티티/기간 추출
2. 카탈로그 메타데이터로 1차 후보 필터
3. 후보만 대상으로 proxy 벡터 검색(top-k)
4. 선택 테이블 실행 후 답변 합성
5. 라우팅 로그 저장(후속 튜닝 데이터)

> 핵심은 "문서를 바로 검색"이 아니라, **정규화된 데이터 자산(테이블+카탈로그)을 먼저 만든 뒤 라우팅**하는 것이다.

In [ ]:
from __future__ import annotations

import re
import time
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import pandas as pd
from llama_index.core import Settings, VectorStoreIndex
from llama_index.core.schema import IndexNode

try:
    from llama_index.experimental.query_engine import PandasQueryEngine
except Exception as e:
    raise ImportError(
        "PandasQueryEngine import failed. Install llama-index-experimental or run earlier setup cells."
    ) from e


# -----------------------------
# 1) Catalog build utilities
# -----------------------------
def _infer_domain_from_columns(columns: List[str]) -> str:
    text = " \".join([str(c).lower() for c in columns])
    rules = {
        "finance": ["revenue", "profit", "asset", "market", "net", "stock", "worth"],
        "people": ["name", "age", "rank", "person", "ceo", "founder"],
        "geo": ["country", "city", "region", "state", "nation"],
        "time": ["date", "year", "month", "quarter"],
    }
    for domain, kws in rules.items():
        if any(k in text for k in kws):
            return domain
    return "other"


def _case_type(df: pd.DataFrame) -> str:
    cols = [str(c).lower() for c in df.columns]
    n_rows, n_cols = df.shape

    if n_rows == 0 or n_cols == 0:
        return "empty_or_invalid"
    if any("date" in c or "year" in c for c in cols):
        return "time_series_table"
    if any("name" in c or "rank" in c for c in cols):
        return "entity_profile_table"
    if n_cols > 20:
        return "wide_analytical_table"
    return "generic_structured_table"


def build_table_catalog(table_dfs: List[pd.DataFrame], source_id: str = "pdf_wiki_billionaires") -> pd.DataFrame:
    rows = []
    now = pd.Timestamp.utcnow()

    for i, df in enumerate(table_dfs):
        safe_df = df.copy()
        safe_df.columns = [str(c).strip() for c in safe_df.columns]
        cols = list(safe_df.columns)

        domain = _infer_domain_from_columns(cols)
        case_type = _case_type(safe_df)
        null_ratio = float(safe_df.isna().mean().mean()) if len(safe_df) else 1.0
        quality_score = max(0.0, min(1.0, 1.0 - null_ratio))

        table_id = f"tbl_{source_id}_{i:04d}"
        profile_text = (
            f"table_id={table_id}; source={source_id}; domain={domain}; case_type={case_type}; "
            f"rows={len(safe_df)}; cols={len(cols)}; columns={', '.join(cols[:25])}"
        )

        rows.append(
            {
                "table_id": table_id,
                "source_id": source_id,
                "table_name": f"{source_id}_table_{i}",
                "domain": domain,
                "case_type": case_type,
                "row_count": int(len(safe_df)),
                "col_count": int(len(cols)),
                "columns": cols,
                "quality_score": quality_score,
                "updated_at": now,
                "profile_text": profile_text,
            }
        )

    return pd.DataFrame(rows)


# ----------------------------------------
# 2) Production-like Router (Practical)
# ----------------------------------------
@dataclass
class RoutingResult:
    answer: str
    candidate_table_ids: List[str]
    selected_table_ids: List[str]
    partial_answers: List[Tuple[str, str]]
    latency_sec: float


class EnterpriseTableRouter:
    """
    메타데이터 기반 1차 필터 + proxy 벡터 라우팅 + lazy 엔진 생성 + 답변 합성
    """

    def __init__(self, table_dfs: List[pd.DataFrame], catalog_df: pd.DataFrame):
        self.table_dfs = table_dfs
        self.catalog = catalog_df.copy()

        # table_id -> df index 연결
        self.table_id_to_df_idx = {
            row.table_id: int(i) for i, row in self.catalog.reset_index(drop=True).iterrows()
        }

        # proxy index
        proxy_nodes = [
            IndexNode(text=row.profile_text, index_id=row.table_id)
            for _, row in self.catalog.iterrows()
        ]
        self.proxy_index = VectorStoreIndex(proxy_nodes)

        # lazy engine cache
        self._engine_cache: Dict[str, PandasQueryEngine] = {}

    def _query_features(self, query: str) -> Dict[str, str]:
        q = query.lower()
        domain = "other"
        if re.search(r"revenue|profit|asset|market|worth|부자|자산", q):
            domain = "finance"
        elif re.search(r"name|age|rank|who|사람|누구|순위", q):
            domain = "people"
        elif re.search(r"country|city|region|국가|도시", q):
            domain = "geo"
        return {"domain": domain}

    def _metadata_filter(self, query: str, min_quality: float = 0.4) -> List[str]:
        feat = self._query_features(query)
        cand = self.catalog[self.catalog["quality_score"] >= min_quality]

        if feat["domain"] != "other":
            narrowed = cand[cand["domain"] == feat["domain"]]
            if len(narrowed) > 0:
                cand = narrowed

        return cand["table_id"].tolist()

    def _route_topk(self, query: str, candidate_ids: List[str], top_k: int = 3) -> List[str]:
        retriever = self.proxy_index.as_retriever(similarity_top_k=max(top_k * 4, top_k))
        hits = retriever.retrieve(query)

        ranked = []
        allow = set(candidate_ids)
        for h in hits:
            node = getattr(h, "node", h)
            tid = getattr(node, "index_id", None)
            if tid and tid in allow and tid not in ranked:
                ranked.append(tid)
            if len(ranked) >= top_k:
                break

        # fallback
        if not ranked:
            ranked = candidate_ids[:top_k]

        return ranked

    def _get_engine(self, table_id: str) -> PandasQueryEngine:
        if table_id not in self._engine_cache:
            df_idx = self.table_id_to_df_idx[table_id]
            self._engine_cache[table_id] = PandasQueryEngine(
                df=self.table_dfs[df_idx],
                llm=Settings.llm,
                verbose=False,
            )
        return self._engine_cache[table_id]

    def query(self, query: str, top_k: int = 3, debug: bool = True) -> RoutingResult:
        t0 = time.time()

        candidate_ids = self._metadata_filter(query)
        selected_ids = self._route_topk(query, candidate_ids, top_k=top_k)

        partial = []
        for tid in selected_ids:
            try:
                ans = self._get_engine(tid).query(query)
                partial.append((tid, str(ans)))
            except Exception as e:
                partial.append((tid, f"[ERROR] {e}"))

        context = "\n\n".join([f"[table_id={tid}]\n{text}" for tid, text in partial])
        prompt = (
            "You are a data synthesis assistant.\n"
            "Create one final answer from partial table answers.\n"
            "If evidence conflicts, explicitly mention conflicts and confidence.\n\n"
            f"User Query: {query}\n\n"
            f"Partial Answers:\n{context}"
        )

        final = Settings.llm.complete(prompt)
        final_text = getattr(final, "text", str(final))
        latency = time.time() - t0

        if debug:
            print("candidate_table_ids:", candidate_ids[:10], f"... total={len(candidate_ids)}")
            print("selected_table_ids:", selected_ids)
            print("lazy_cache_size:", len(self._engine_cache))
            print("latency_sec:", round(latency, 3))

        return RoutingResult(
            answer=final_text,
            candidate_table_ids=candidate_ids,
            selected_table_ids=selected_ids,
            partial_answers=partial,
            latency_sec=latency,
        )


# ----------------------------------------
# 3) Run with existing notebook variables
# ----------------------------------------
if "table_dfs" not in globals():
    raise ValueError("table_dfs not found. Run table extraction cells first.")

catalog_df = build_table_catalog(table_dfs=table_dfs, source_id="billionaire_pdf")
display(catalog_df[["table_id", "domain", "case_type", "row_count", "col_count", "quality_score"]].head())

enterprise_router = EnterpriseTableRouter(table_dfs=table_dfs, catalog_df=catalog_df)

sample_query = "가장 부자인 사람은 누구이고 어느 국가 출신이야?"
result = enterprise_router.query(sample_query, top_k=3, debug=True)
print(result.answer)